Repository wpeverest/everest-forms, pull requests merged in 2018-06, with the labels that each got.

#25 Migrating settings option name
  includes/admin/settings/class-evf-settings-email.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/admin/settings/class-evf-settings-validation.php
  includes/admin/views/html-admin-settings.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/class-evf-install.php
  includes/evf-update-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
  uninstall.php
Labels: Status: Approved

#26 Refactor/settings UI
  assets/css/_fonts.scss
  assets/css/_mixins.scss
  assets/css/_variables.scss
  assets/css/admin-rtl.css
  assets/css/admin-settings-rtl.css
  assets/css/admin-settings.css
  assets/css/admin-settings.scss
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-builder.scss
  assets/css/scss/_admin.scss
  assets/css/scss/_colors.scss
  assets/css/scss/_evf-icon.scss
  assets/fonts/evf-icon.eot
  assets/fonts/evf-icon.svg
  assets/fonts/evf-icon.ttf
  assets/fonts/evf-icon.woff
  assets/js/admin/everest-forms-admin.js
  assets/js/admin/settings.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-email.php
  includes/admin/settings/class-evf-settings-general.php
  includes/admin/settings/class-evf-settings-page.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/admin/settings/class-evf-settings-validation.php
  includes/admin/views/html-admin-settings.php
  includes/class-evf-background-updater.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/class-evf-install.php
  includes/class-evf-post-types.php
  includes/evf-core-functions.php
  includes/evf-update-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
  uninstall.php
Labels: Status: Approved

#24 serialized meta_value including html tags
  includes/admin/views/html-admin-page-entries-view.php
Labels: Status: Needs review

#27 Refactor form builder UI
  assets/css/_animation.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/scss/_admin.scss
  assets/images/icons/loader.svg
  assets/images/icons/three-dots.svg
  assets/js/admin/everest-forms-admin.min.js
  assets/js/admin/everest-panel-builder.js
  assets/js/admin/everest-panel-builder.min.js
  assets/js/admin/settings.min.js
  includes/abstracts/abstract-evf-admin-form-panel.php
  includes/admin/class-evf-admin-form-builder.php
  includes/admin/class-evf-admin.php
  includes/admin/form-panels/class-evf-fields-panel.php
  includes/class-evf-ajax.php
  includes/evf-conditional-functions.php
  includes/evf-core-functions.php
  includes/evf-user-functions.php
  package-lock.json
  package.json
Labels: Status: Approved, enhancement

#28 Load form fields via autoloader class for call them on demand
  includes/admin/class-evf-admin-menus.php
  includes/class-everest-forms.php
  includes/class-evf-autoloader.php
  includes/class-evf-field-item.php
  includes/class-evf-fields.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-date.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-first-name.php
  includes/fields/class-evf-field-last-name.php
  includes/fields/class-evf-field-number.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
  includes/fields/class-evf-field-url.php
Labels: Status: Needs review, enhancement

#29 Deprecated hook handling
  includes/abstracts/class-evf-deprecated-hooks.php
  includes/class-everest-forms.php
  includes/class-evf-deprecated-action-hooks.php
  includes/class-evf-deprecated-filter-hooks.php
  includes/class-evf-fields.php
Labels: Status: Approved, enhancement

#31 Tweak - Add fields toggle actions
  assets/js/admin/form-builder.js
Labels: Status: Needs review, enhancement

#32 Fix - copy shortcode tipTip effect on hover and on click
  assets/js/admin/form-builder.js
  includes/admin/views/html-admin-page-builder.php
Labels: Status: Approved, enhancement

#33 Backward compatibility for removed EVF builder pages
  includes/admin/class-evf-admin-menus.php
Labels: Status: Needs review, bug

#34 Deprecated - everest_forms_sanitize_textarea_field to evf_sanitize_textarea_field
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-evf-form-fields.php
  includes/class-evf-emails.php
  includes/evf-core-functions.php
  includes/evf-deprecated-functions.php
  includes/fields/class-evf-field-textarea.php
Labels: Improved-pr, Status: Approved
