Repository wpeverest/everest-forms, pull requests merged in 2018-12, with the labels that each got.

#49 Tweak - Design for multiple email notification area
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/scss/_admin.scss
  includes/admin/builder/class-evf-builder-settings.php
Labels: Improved-pr, Status: Needs review

#51 Fix - Form block styles not loaded in WP 5.0
  includes/class-evf-form-block.php
Labels: Status: Approved, bug

#52 Conditionally load assets
  includes/class-evf-frontend-scripts.php
  includes/evf-core-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Status: Approved, enhancement

#53 Feature/smart tags
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
  assets/css/scss/_admin.scss
  assets/js/admin/form-builder.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/evf-admin-functions.php
  includes/class-evf-deprecated-filter-hooks.php
  includes/class-evf-form-task.php
  includes/class-evf-smart-tags.php
  includes/shortcodes/class-evf-shortcode-form.php
  includes/templates/contact.php
Labels: Status: Needs review, enhancement

#55 Fix - reCAPTCHA conflict during validation if multiple forms are present
  assets/js/frontend/everest-forms.js
  composer.lock
  includes/class-evf-frontend-scripts.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: bug
