Repository wpeverest/everest-forms, pull requests merged in 2019-11, with the labels that each got.

#292 Tweak - CSS for label and radio/checkbox field
  assets/css/_variables.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#296 Fixes - WordPress 5.3 UI compatibility bug
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: [Status] Ready to Merge, bug

#298 Tweak - Design tweaks
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/select2.css
  assets/css/select2.scss
  includes/admin/class-evf-admin-forms-table-list.php
Labels: [Status] Ready to Merge

#295 Feature - Email field mailcheck feature to offer additional controls
  .eslintrc
  Gruntfile.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  assets/js/mailcheck/mailcheck.js
  assets/js/mailcheck/mailcheck.min.js
  includes/admin/settings/class-evf-settings-validation.php
  includes/class-evf-frontend-scripts.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Q3, [Status] Ready to Merge

#297 Tweak - Seperate site and secret key for recaptcha v2 invisible
  assets/js/admin/settings.js
  includes/admin/settings/class-evf-settings-recaptcha.php
Labels: Enhancement, Q3, [Status] Ready to Merge

#294 Field - Date and time field enhancement
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/admin/settings.js
  assets/js/admin/settings.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/fields/class-evf-field-date-time.php
  languages/everest-forms.pot
Labels: Enhancement, Q3, [Status] Needs Docs, [Status] Ready to Merge
