Repository wpeverest/everest-forms, pull requests merged in 2019-04, with the labels that each got.

#110 Prevent content filters from corrupting JSON in post_content.
  includes/class-evf-form-handler.php
Labels: [Status] Ready to Merge, bug

#113 Fix - two column grid issue in responsive
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Good first issue, [Status] Needs Review

#125 Add - miscellaneous icon font
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
Labels: Enhancement

#134 Tweak - Design enhancement
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/scss/_admin.scss
Labels: Enhancement, [Status] Ready to Merge
