Repository wpeverest/everest-forms, pull requests merged in 2019-06, with the labels that each got.

#179 Fix - WP admin bar design issue in safari on EVF pages
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: [Status] Needs Review, bug

#189 Feature - New entries "heartbeat" notification on the entries list table screen
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-entries.php
  includes/evf-entry-functions.php
Labels: Enhancement, [Status] Ready to Merge

#185 Feature - New "Range" option for Date
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/frontend/everest-forms.js
  includes/fields/class-evf-field-date-time.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Ready to Merge

#190 Fix - Form builder design bug on wp.com dashboard
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.min.js
  includes/admin/views/html-admin-page-builder.php
Labels: [Status] Ready to Merge, bug

#196 Fix - Dragging forms fields from the builder
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
Labels: [Status] Ready to Merge, bug

#192 Feature - Form specific email notification toggle
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-form-task.php
  languages/everest-forms.pot
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge
