Repository wpeverest/everest-forms, pull requests merged in 2019-09, with the labels that each got.

#254 Fix/translation issue
  includes/class-evf-ajax.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Review, bug

#255 Fix - Multi-part form conflict in frontend single page
  includes/admin/builder/class-evf-builder-fields.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Improved-pr, [Status] Ready to Merge, bug

#260 Fix sortable scroll
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: [Status] Ready to Merge

#257 Fix - Field not appended in the droppable zone
  .eslintrc
  Gruntfile.js
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/flatpickr/flatpickr.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  assets/js/jquery-blockui/jquery.blockUI.min.js
  assets/js/selectWoo/selectWoo.min.js
  assets/js/tooltipster/tooltipster.bundle.min.js
Labels: [Status] Ready to Merge, bug

#248 Feature/confirm email
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-email.php
Labels: Enhancement, [Status] Needs Docs, [Status] Needs Review

#265 Introduced welcome page
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/images/welcome-video-thumb.png
  assets/js/admin/admin.js
  includes/admin/class-evf-admin-welcome.php
  includes/admin/class-evf-admin.php
  includes/admin/evf-admin-functions.php
  includes/class-evf-install.php
Labels: Enhancement, [Status] In Progress, [Status] Needs Review
