Repository wpeverest/everest-forms, pull requests merged in 2019-08, with the labels that each got.

#234 Fix - CSV export broken due to uppercase alphanumric meta-key
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/class-evf-form-handler.php
  includes/export/class-evf-entry-csv-exporter.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug

#243 Feature- Review notice
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/activation.scss
  includes/admin/class-evf-admin-notices.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-notice-review.php
  includes/class-evf-ajax.php
  includes/class-evf-install.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#235 [README] Rolling readme for 1.5.4
  CHANGELOG.txt
  package.json
  readme.txt
Labels: [Status] Ready to Merge
