Repository wpeverest/everest-forms, pull requests merged in 2019-12, with the labels that each got.

#314 Fix accessing curl arr index warning due to likely deprecation [PHP5.6]
  includes/evf-formatting-functions.php
Labels: bug

#315 Provisioning for better error handling
  includes/class-everest-forms.php
Labels: [Status] Ready to Merge, bug

#309 Enhanced - Single Line Text/Paragraph fields limitation options
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.min.js
  assets/js/frontend/text-limit.js
  assets/js/frontend/text-limit.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-frontend-scripts.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
  phpcs.xml
Labels: Enhancement, Q3, [Status] Needs Docs, [Status] Ready to Merge

#326 Tweak - Editable Form name from the form builder title
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/class-evf-admin-assets.php
Labels: Q3, [Status] Needs Review

#317 Tweak - Referal in admin panel for origination of form entry
  includes/admin/views/html-admin-page-entries-view.php
Labels: Enhancement, Q3, [Status] Ready to Merge
