Repository wpeverest/everest-forms, pull requests merged in 2019-03, with the labels that each got.

#69 Added dimension related formatting functions
  includes/evf-formatting-functions.php
Labels: enhancement

#73 Tweak - styles for address field
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: bug

#74 Fix/input styles
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Status: Approved, enhancement

#75 Fix - spacing between two form on single page
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Status: Approved, good first issue

#72 Scroll to top bug fix
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/select2.css
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  languages/everest-forms.pot
  package-lock.json
Labels: Status: Approved, bug

#59 Rolling 1.4.5 readme
  CHANGELOG.txt
  everest-forms.php
  includes/class-everest-forms.php
  package-lock.json
  package.json
  readme.txt
  webpack.config.js
Labels: Status: In Progress

#68 Appearance selector
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Status: Approved, bug

#80 Feature/survey polls quiz
  Gruntfile.js
  assets/css/_variables.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/scss/_admin.scss
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-everest-forms.php
  includes/class-evf-form-task.php
  includes/class-evf-forms-features.php
  includes/evf-conditional-functions.php
  includes/evf-core-functions.php
  includes/evf-notice-functions.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-likert.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-rating.php
  includes/fields/class-evf-field-score-rating.php
  includes/shortcodes/class-evf-shortcode-form.php
  languages/everest-forms.pot
  package-lock.json
  templates/notices/success.php
Labels: Improved-pr, Status: Approved, enhancement

#92 Bugfix/setting perfect scrollbar
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/scss/_admin.scss
  assets/css/select2.css
  assets/js/admin/form-builder.js
Labels: bug

#93 Replace - tipTip with Tooltipster
  .eslintignore
  Gruntfile.js
  assets/css/_animation.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/scss/_admin.scss
  assets/css/select2.css
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/tooltipster/tooltipster.bundle.js
  assets/js/tooltipster/tooltipster.bundle.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/evf-admin-functions.php
Labels: Status: Approved

#94 Feature: Add support for signature field
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-signature.php
Labels: Status: In Progress, enhancement

#95 Tweak - likert and scale-rating icons
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/select2.css
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
Labels: Status: Approved, status: needs feedback
