Repository wpeverest/everest-forms, pull requests merged in 2019-07, with the labels that each got.

#184 Tweak - UI improvements
  assets/css/_animation.scss
  assets/css/_backbone.scss
  assets/css/_clearings.scss
  assets/css/_colors.scss
  assets/css/_confirm.scss
  assets/css/_variables.scss
  assets/css/activation.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
Labels: Enhancement, Improved-pr, [Status] Needs Changelog, [Status] Ready to Merge

#201 Fix - Date and time field option and responsive design
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement, [Status] Needs Review

#202 Tweak - Removed unnecessary CSS to fix Multi-part button alignment
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
Labels: [Status] Ready to Merge, bug

#165 Use WP 5.0 determine_locale() function
  includes/class-everest-forms.php
Labels: Improved-pr, [Status] Ready to Merge

#199 [README] Rolling readme for 1.5.0
  everest-forms.php
  includes/admin/class-evf-admin-entries.php
  includes/class-everest-forms.php
  includes/evf-entry-functions.php
  includes/fields/class-evf-field-email.php
  languages/everest-forms.pot
  package-lock.json
  package.json
  readme.txt
Labels: [Status] Ready to Merge

#208 [Addon] User Registration support
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.js
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Ready to Merge

#212 Tweak - Drag and drop sortable-ui design enhancement on sidebar panel
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
Labels: Enhancement, [Status] Ready to Merge, bug

#213 Fix - Form notices for frontend
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
  package.json
  readme.txt
Labels: [Status] Ready to Merge, bug

#219 Field type changed from date to date-time
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  includes/admin/class-evf-admin-settings.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement, [Status] Needs Review

#220 Tweak - Screenshots updated
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-128x128.svg
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-10.jpg
  .wordpress-org/screenshot-11.jpg
  .wordpress-org/screenshot-12.jpg
  .wordpress-org/screenshot-2.jpg
  .wordpress-org/screenshot-3.jpg
  .wordpress-org/screenshot-4.jpg
  .wordpress-org/screenshot-5.jpg
  .wordpress-org/screenshot-6.jpg
  .wordpress-org/screenshot-7.jpg
  .wordpress-org/screenshot-8.jpg
  .wordpress-org/screenshot-9.jpg
Labels: Enhancement, [Status] Ready to Merge

#221 Field choices preview fixed while removing field choices
  assets/js/admin/form-builder.js
Labels: [Status] Ready to Merge, bug

#227 Fix - Entries form filter action bug while paginated
  includes/admin/class-evf-admin-entries.php
Labels: [Status] Ready to Merge, bug

#228 Fix - Bulk actions for entries list table
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin-menus.php
Labels: [Status] Ready to Merge, bug
