Repository wpeverest/everest-forms, pull requests merged in 2019-05, with the labels that each got.

#136 Fix - Form Block additional CSS returning error
  assets/js/admin/gutenberg/form-block.js
  assets/js/admin/gutenberg/form-block.min.js
  includes/class-evf-form-block.php
  package-lock.json
  package.json
Labels: Improved-pr, [Status] Ready to Merge, bug

#137 Tweak - Rearrange sass files
  assets/css/_backbone.scss
  assets/css/_clearings.scss
  assets/css/_colors.scss
  assets/css/_confirm.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/everest-builder.scss
  assets/css/everest-forms.scss
  assets/css/scss/_admin.scss
Labels: Enhancement, [Status] Ready to Merge

#124 Fix - Other content sections hiding on payment gateway tab click
  assets/js/admin/form-builder.js
Labels: [Status] Ready to Merge, bug

#135 Email Notifications and Smart Tags enhancement
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-builder-rtl.css
  assets/css/everest-builder.css
  assets/css/scss/_admin.scss
  assets/js/admin/evf-admin-email.js
  assets/js/admin/form-builder.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/evf-admin-functions.php
  includes/templates/contact.php
  package-lock.json
Labels: Enhancement, [Status] Ready to Merge, bug

#140 Submit button class/classes
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/admin/builder/class-evf-builder-settings.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Review

#138 Tweak - Input styles inherited from theme's style
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#145 Tweak - Edit form link in form preview
  includes/class-evf-template-loader.php
Labels: Enhancement, [Status] Ready to Merge

#146 Tweak - Button design consistence
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/menu.scss
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/views/html-admin-page-builder.php
  includes/admin/views/html-admin-settings.php
Labels: Enhancement, [Status] Ready to Merge

#147 Fix - Ui-dragging
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: [Status] Ready to Merge, bug

#148 Fix - Display a "Copied!" tip when success copying
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/admin/evf-admin-email.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
Labels: [Status] Needs Review, bug

#122 Feature - Time support and advanced formatting options for a date field.
  assets/css/_clearings.scss
  assets/css/_colors.scss
  assets/css/_confirm.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/scss/_admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-fields.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-date.php
Labels: Enhancement, [Status] Needs Review

#139 Define wpdb tables as early as possible, before init
  includes/class-everest-forms.php
Labels: [Status] Ready to Merge

#77 Number field min max support
  assets/js/admin/admin.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/fields/class-evf-field-number.php
Labels: Enhancement, Good first issue, [Status] Needs Review

#152 Enhancement - Submit button conditional logic
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  includes/admin/builder/class-evf-builder-settings.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Ready to Merge

#129 Enhancement - CC and BCC added to email notification
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/settings/class-evf-settings-email.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
Labels: Enhancement, [Status] Ready to Merge

#154 Feature - Introduced Credit card field for stripe
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/upgrade.js
  assets/js/admin/upgrade.min.js
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-credit-card.php
  includes/fields/class-evf-field-payment-charge-options.php
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge

#155 Fixed node depedencies with npm audit fix
  package-lock.json
Labels: [Status] Ready to Merge

#160 Tweak - Email template radio-image
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/images/email-template-html.png
  assets/images/email-template-plain.png
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-email.php
  languages/everest-forms.pot
  package-lock.json
Labels: Enhancement, [Status] Needs Author Reply

#157 Feature - reCaptcha V2 invisible and V3
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/js/admin/settings.js
  assets/js/admin/settings.min.js
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/class-evf-form-task.php
  includes/class-evf-install.php
  includes/evf-update-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge

#163 Tweak - Tooltip information enhancements
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/settings/class-evf-settings-recaptcha.php
Labels: Enhancement, [Status] Ready to Merge

#162 Feature - Anti-spam honeypot form field for spam protection.
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
  includes/templates/contact.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#164 Fix: Builder CSS doesn't exist
  includes/admin/class-evf-admin-assets.php
Labels: [Status] Ready to Merge, bug

#166 Field attr structure on email and Cc, Bcc support on multiple email.
  assets/js/admin/evf-admin-email.js
  includes/admin/builder/class-evf-builder-settings.php
Labels: Improved-pr, [Status] Ready to Merge

#169 Submit conditional process only when conditional logic is enabled
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug

#168 Fix tooltip issue on email new notifications
  assets/js/admin/admin.js
Labels: [Status] Ready to Merge, bug

#170 Design changes for info messages
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: Enhancement, [Status] Ready to Merge

#161 Feature - WPML compatible
  includes/evf-core-functions.php
  includes/evf-notice-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
  wpml-config.xml
Labels: Enhancement, [Status] Ready to Merge

#156 Performance: caching of template loader
  includes/evf-core-functions.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#174 Fix translation for placeholder
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Improved-pr, [Status] Ready to Merge

#153 Form submit handler
  assets/js/frontend/everest-forms.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
  templates/notices/success.php
Labels: Enhancement, [Status] Ready to Merge

#177 Fix - Submit button Processing text while form is not saved
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug
