Repository wpeverest/everest-forms, pull requests merged in 2020-01, with the labels that each got.

#321 Feature - Import Export of Everest Forms
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/admin/form-builder.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-import-export.php
  includes/admin/class-evf-admin-menus.php
  includes/admin/class-evf-admin-tools.php
  includes/admin/class-evf-admin.php
  includes/admin/evf-admin-functions.php
  includes/admin/views/html-admin-page-builder.php
  includes/admin/views/html-admin-page-export.php
  includes/admin/views/html-admin-page-import.php
  includes/admin/views/html-admin-page-tools-logs.php
  includes/admin/views/html-admin-page-tools.php
  includes/class-evf-ajax.php
Labels: Enhancement, Q3, [Status] Needs Docs, [Status] Ready to Merge

#330 Tweak - Sorting with template plan types
  assets/js/admin/form-template-controller.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/views/html-admin-page-builder-setup.php
Labels: Enhancement, [Status] Ready to Merge

#351 Tweak - Styles for progress bar
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
Labels: Enhancement, [Status] Needs Review

#350 Fix - Specific form submission notice display in another.
  includes/evf-notice-functions.php
Labels: [Status] Ready to Merge

#333 Enhance - Address field's sub labels made editable
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge
