Repository wpeverest/everest-forms, pull requests merged in 2020-07, with the labels that each got.

#404 Addon - Form restriction
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/select2.css
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Review

#449 Fix - Conditional logic number field
  CHANGELOG.txt
  assets/css/admin.scss
  includes/fields/class-evf-field-number.php
  package-lock.json
Labels: [Status] Ready to Merge, bug

#419 Enhance - Show total unread entries count in the main menu
  includes/admin/class-evf-admin-menus.php
Labels: Enhancement, Q4, [Status] Ready to Merge

#411 Feature - Privacy Policy field
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/class-evf-emails.php
  includes/class-evf-forms-features.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-privacy-policy.php
Labels: Feature Branch 🚀

#475 Dashboard analytics feature
  assets/css/_badge.scss
  assets/css/_buttons.scss
  assets/css/_card.scss
  assets/css/_colors.scss
  assets/css/_fonts.scss
  assets/css/_grid.scss
  assets/css/_table.scss
  assets/css/_variables.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/utility/_display.scss
  assets/css/utility/_spacing.scss
  assets/js/admin/admin.js
  includes/class-evf-form-task.php
  includes/evf-core-functions.php
  includes/evf-entry-functions.php
  package-lock.json
Labels: Enhancement, Q4, [Status] Ready to Merge

#425 Feature - Editable entries
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  includes/abstracts/class-evf-form-fields.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/evf-core-functions.php
  includes/evf-entry-functions.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
Labels: Q4, [Status] Ready to Merge

#439 Enhance - Add bulk choice
  assets/js/admin/form-builder.js
  assets/js/admin/upgrade.js
  includes/abstracts/class-evf-form-fields.php
  includes/evf-core-functions.php
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge

#461 Feature - Stripe recurring payment
  includes/admin/views/html-admin-page-entries-view.php
Labels: Q4, [Status] Ready to Merge, bug

#476 Enhance - Export quiz to CSV
  includes/class-evf-form-task.php
  includes/export/abstract-evf-csv-exporter.php
  includes/export/class-evf-entry-csv-exporter.php
Labels: Enhancement, [Status] Ready to Merge

#482 Fix: WP color field initialization when multi-part addon is enabled
  assets/js/admin/admin.js
Labels: Q4, [Status] Ready to Merge

#456 Introduced script to generate a zip package
  bin/build-zip.sh
  package.json
Labels: Enhancement, [Status] Ready to Merge

#440 Tweak - Introduced filter to disable reCAPTCHA check for logged-in user
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Ready to Merge

#487 Fix - reCAPTCHA working only for logged in user
  CHANGELOG.txt
  includes/class-evf-deprecated-filter-hooks.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug

#486 Fix - Form toggle button
  CHANGELOG.txt
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
Labels: [Status] Ready to Merge, bug

#485 Fix - Email subject while using select field smart tag
  CHANGELOG.txt
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#488 Fix - Select field placeholder not displayed and selected
  includes/fields/class-evf-field-select.php
Labels: [Status] Ready to Merge, bug

#493 Fix - Conditional logic on select field
  includes/fields/class-evf-field-select.php
Labels: [Status] Needs Review, bug
