Repository wpeverest/everest-forms, pull requests merged in 2020-09, with the labels that each got.

#517 Addon - Email Templates
  assets/css/_confirm.scss
  assets/css/_grid.scss
  assets/css/activation.css.map
  assets/css/activation.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.css.map
  assets/css/admin.scss
  assets/css/components/_badge.scss
  assets/css/components/_buttons.scss
  assets/css/components/_card.scss
  assets/css/components/_table.scss
  assets/css/everest-forms.css.map
  assets/css/everest-forms.scss
  assets/css/flatpickr.css.map
  assets/css/menu.css.map
  assets/css/menu.scss
  assets/css/mixins/_breakpoints.scss
  assets/css/mixins/_grids.scss
  assets/css/mixins/_mixins.scss
  assets/css/select2.css.map
  assets/css/utility/_border.scss
  assets/css/utility/_display.scss
  assets/css/utility/_spacing.scss
  assets/css/variables/_colors.scss
  assets/css/variables/_grids.scss
  assets/css/variables/_variables.scss
  assets/js/admin/evf-setup.js
  includes/admin/evf-admin-functions.php
  includes/admin/views/html-admin-page-builder-setup.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
Labels: Feature Branch 🚀, [Status] Needs Docs

#516 Enhancement - Addon/google sheets
  includes/abstracts/class-evf-integration.php
  includes/admin/class-evf-admin-settings.php
  includes/class-evf-ajax.php
Labels: Feature Branch 🚀, Improved-pr, [Status] Ready to Merge

#509 Feature - Multiple choices/options selection
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_buttons.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/select2.css
  assets/css/select2.scss
  assets/js/admin/evf-setup.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/admin/upgrade.js
  assets/js/admin/upgrade.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-select.php
Labels: Enhancement, [Status] Needs Review, bug
