Repository wpeverest/everest-forms, pull requests merged in 2020-03, with the labels that each got.

#379 Fix - Import export file name issue
  includes/admin/class-evf-admin-import-export.php
Labels: [Status] Needs Review, bug

#386 Fix - Google reCAPTCHA issue with the version changes
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Improved-pr, [Status] Ready to Merge, bug

#387 Tweak - Remove smart tags icon from default value option for Number field.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/abstracts/class-evf-form-fields.php
  package-lock.json
Labels: [Status] Ready to Merge, bug

#383 Use WP-CLI i18n command instead of legacy grunt packages
  Gruntfile.js
  composer.json
  composer.lock
  includes/admin/views/html-admin-page-addons.php
  languages/everest-forms.pot
  package-lock.json
  package.json
Labels: [Status] Ready to Merge
