Repository wpeverest/everest-forms, pull requests merged in 2020-10, with the labels that each got.

#525 Fix - Message for required file upload field
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, bug

#526 [Enhancement] - Add Search Fields on builder page
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_forms.scss
  assets/css/variables/_colors.scss
  assets/images/fields-not-found.png
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  bin/post-merge.sh
  includes/admin/builder/class-evf-builder-fields.php
  package-lock.json
  package.json
Labels: Enhancement, [Status] Needs Review

#534 Fix - Search fields feature misbehaving
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.min.js
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, bug

#535 Form template plan name
  includes/admin/views/html-admin-page-builder-setup.php
Labels: Improved-pr, [Status] Ready to Merge
