Repository wpeverest/everest-forms, pull requests merged in 2020-02, with the labels that each got.

#334 Fix - reCAPTCHA when running on localhost with port different from 80
  includes/class-evf-form-task.php
Labels: [Status] Ready to Merge, bug

#354 Feature- Add support for form template
  .eslintrc
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/images/templates/advanced-contact-form.png
  assets/images/templates/blank.png
  assets/images/templates/donation-form.png
  assets/images/templates/job-vacancy-form.png
  assets/images/templates/leave-request-form.png
  assets/images/templates/medical-appointment-form.png
  assets/images/templates/new-form.png
  assets/images/templates/restaurant-table-booking.png
  assets/images/templates/simple-contact-form.png
  assets/images/templates/simple-support-form.png
  assets/images/templates/survey-form.png
  assets/js/admin/evf-setup.js
  assets/js/admin/extensions.js
  assets/js/admin/form-template-controller.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-admin-page-builder-setup.php
  includes/class-evf-ajax.php
  includes/class-evf-form-handler.php
Labels: Enhancement, [Status] Ready to Merge

#331 Enhanced - Improve choice field with image support
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/images/everest-forms-placeholder.png
  assets/images/placeholder.png
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/abstracts/legacy/class-evf-admin-form-panel.php
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/builder/class-evf-builder-page.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/settings/class-evf-settings-validation.php
  includes/admin/views/html-admin-page-builder.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/shortcodes/class-evf-shortcode-form.php
  phpcs.xml
Labels: Enhancement, Improved-pr, [Status] Needs Docs, [Status] Needs Review, [Status] Needs design, bug

#352 Enhanced - Improve entries with different actions
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-everest-forms.php
  includes/class-evf-form-task.php
  includes/class-evf-install.php
  includes/evf-entry-functions.php
  includes/evf-update-functions.php
  includes/export/class-evf-entry-csv-exporter.php
Labels: Enhancement, Improved-pr, [Status] Needs Docs, bug

#358 Fix - conflict between error messages and move confirm field
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/admin/settings/class-evf-settings-validation.php
  includes/class-evf-frontend-scripts.php
Labels: [Status] Ready to Merge, bug

#357 Feature - Ajax form submission
  assets/js/frontend/ajax-submission.js
  assets/js/frontend/everest-forms.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-ajax.php
  includes/class-evf-emails.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-number.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Docs, [Status] Ready to Merge

#359 Updated Privacy Policy Guide to use proper classes
  includes/class-evf-privacy.php
Labels: Improved-pr, [Status] Ready to Merge

#368 Fix - Smart tags of multiple choice fields and checkbox fields not working in email
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#369 Fix - Error thrown for star rating field when using smart tags.
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#371 Fix - conditional logic fix for checkbox/radio
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-radio.php
Labels: [Status] Needs Review, bug

#375 Fix - redirection parameter delegated to frontend for successful AJAX form submission
  assets/js/admin/form-builder.js
  assets/js/frontend/ajax-submission.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-form-task.php
Labels: [Status] Needs Review, bug

#376 Tweak - Email Tweaks
  includes/fields/class-evf-field-email.php
Labels: [Status] Ready to Merge

#373 Log file cleanup/purge
  includes/class-evf-install.php
  includes/class-evf-logger.php
  includes/evf-core-functions.php
  includes/log-handlers/class-evf-log-handler-file.php
  uninstall.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge
