Repository wpeverest/everest-forms, pull requests merged in 2020-04, with the labels that each got.

#394 Tweak - Use apply_shortocodes() as an alias for do_shortcode()
  includes/class-everest-forms.php
  includes/class-evf-template-loader.php
  includes/evf-core-functions.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#397 Fix - Shortcode design issue in list table
  includes/admin/class-evf-admin-forms-table-list.php
Labels: [Status] Ready to Merge, bug

#398 Fix - WPML compatibility now supported for choice fields
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-radio.php
Labels: bug

#390 Fix - Selective html tag support in field label
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-number.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug

#400 QoL - Edge case addressing.
  includes/class-evf-ajax.php
Labels: Q4, [Status] Ready to Merge, bug

#399 [WIP] - WPML + Polylang compatibility
  includes/abstracts/class-evf-form-fields.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-text.php
  includes/shortcodes/class-evf-shortcode-form.php
  wpml-config.xml
Labels: Improved-pr, Q4, [Status] In Progress, bug

#406 Tweak - Prefill field value so it can be used to modify data
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-email.php
Labels: Improved-pr, Q4, [Status] Needs Review

#407 Tweak - Custom Captcha field now shown as part of pro fields.
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-captcha.php
Labels: bug

#418 Update GH Actions workflow to support assets/readme update
  .github/workflows/push-asset-readme-update.yml
  .github/workflows/push-deploy.yml
Labels: [Status] Ready to Merge

#420 Fix - Perfect scrollbar in RTL
  assets/js/admin/form-builder.js
  assets/js/perfect-scrollbar/perfect-scrollbar.js
  assets/js/perfect-scrollbar/perfect-scrollbar.min.js
  includes/admin/class-evf-admin-assets.php
Labels: [Status] Ready to Merge, bug

#430 Fix - False positive required message upon email validation
  includes/fields/class-evf-field-email.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Q4, [Status] Ready to Merge, bug

#405 Enhance - Added option to disable certain dates in the Date/Time field
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  includes/admin/class-evf-admin-assets.php
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement, [Status] Ready to Merge

#409 Fix - Field option sections get freezed
  assets/js/admin/form-builder.js
Labels: [Status] Needs Review, bug

#410 Enhance - Add ehnanced select feature to the Dropdown field
  CHANGELOG.txt
  assets/js/admin/form-builder.min.js
  assets/js/admin/upgrade.js
  assets/js/admin/upgrade.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-frontend-scripts.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-select.php
  readme.txt
Labels: Enhancement, [Status] Needs Review
