Repository wpeverest/everest-forms, pull requests merged in 2021-12, with the labels that each got.

#773 EVF-202 Fix - Color Picker in Icon Color of Ratings field
  assets/js/admin/admin.js
  changelog.txt
Labels: bug, Tested, Approved

#782 Enhancement - No Duplicate field option added.
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-email.php
Labels: Enhancement, [Status] Ready to Merge

#791 EVF-204 Enhancement - Keyboard Shortcut in Form Builder
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
Labels: Enhancement, [Status] Ready to Merge

#790 EVF-242 Feature - Populate form field via query string
  assets/js/admin/form-builder.js
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement, [Status] Ready to Merge

#792 Enhancement - Conditional logic
  assets/js/admin/form-builder.js
  changelog.txt
Labels: Enhancement, Good first issue, [Status] Ready to Merge, [Status] Needs Changelog

#800 Tweak - Templates and addons JSON pinged from assets
  assets/extensions-json/addon-sections.json
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/activecampaign.png
  assets/extensions-json/sections/images/campaign-monitor.png
  assets/extensions-json/sections/images/convertkit.png
  assets/extensions-json/sections/images/custom-captcha.png
  assets/extensions-json/sections/images/email-templates.png
  assets/extensions-json/sections/images/form-abandonment.png
  assets/extensions-json/sections/images/form-restriction.png
  assets/extensions-json/sections/images/geolocation.png
  assets/extensions-json/sections/images/google-sheets.png
  assets/extensions-json/sections/images/mailchimp.png
  assets/extensions-json/sections/images/mailerlite.png
  assets/extensions-json/sections/images/multi-part-forms.png
  assets/extensions-json/sections/images/offline-forms.png
  assets/extensions-json/sections/images/payment-paypal.png
  assets/extensions-json/sections/images/payment-stripe.png
  assets/extensions-json/sections/images/pdf-submission.png
  assets/extensions-json/sections/images/post-submissions.png
  assets/extensions-json/sections/images/repeater-fields.jpg
  assets/extensions-json/sections/images/save-and-continue.jpg
  assets/extensions-json/sections/images/style-customizer.png
  assets/extensions-json/sections/images/survey-polls-quiz.png
  assets/extensions-json/sections/images/user-registration.png
  assets/extensions-json/sections/images/zapier.png
  assets/extensions-json/templates/all_templates.json
  assets/extensions-json/templates/images/Advanced Contact Form.png
  assets/extensions-json/templates/images/Donation Form.png
  assets/extensions-json/templates/images/Job Vacancy Form.png
  assets/extensions-json/templates/images/Survey Form.png
  assets/extensions-json/templates/images/advanced-contact-form.png
  assets/extensions-json/templates/images/design-agency-request-a-quote.png
  assets/extensions-json/templates/images/donation-form.png
  assets/extensions-json/templates/images/ebook-form.png
  assets/extensions-json/templates/images/hotel-booking.png
  assets/extensions-json/templates/images/job-vacancy-form.jpg
  assets/extensions-json/templates/images/leave-request-form.png
  assets/extensions-json/templates/images/medical-appointment-form.png
  assets/extensions-json/templates/images/modeling-application-form.jpg
  assets/extensions-json/templates/images/new-form.png
  assets/extensions-json/templates/images/restaurant-table-booking.png
  assets/extensions-json/templates/images/simple-contact-form.png
  assets/extensions-json/templates/images/simple-registration.png
  assets/extensions-json/templates/images/simple-support-form.png
  assets/extensions-json/templates/images/style-customizer.png
  assets/extensions-json/templates/images/survey-form.png
  assets/extensions-json/templates/template_sections.json
  assets/js/admin/form-template-controller.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-addons.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-admin-page-addons.php
  includes/admin/views/html-admin-page-builder-setup.php
  includes/class-evf-ajax.php
  includes/class-evf-form-handler.php
Labels: Enhancement, [Status] Needs Review

#799 Fix - Sanitization and escaping issue
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/evf-formatting-functions.php
Labels: bug, [Status] Needs Review

#805 Fix - Escaping issue
  includes/abstracts/class-evf-form-fields.php
  includes/abstracts/class-evf-settings-api.php
  includes/admin/class-evf-admin-import-export.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/evf-core-functions.php
  includes/export/class-evf-entry-csv-exporter.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-textarea.php
  includes/shortcodes/class-evf-shortcode-form.php
  templates/emails/header-default.php
Labels: bug, [Status] Needs Review
