Repository wpeverest/everest-forms, pull requests merged in 2021-11, with the labels that each got.

#759 Fix - Calendar not showing when enable min and max Date
  assets/js/admin/form-builder.js
  changelog.txt
Labels: bug, [Status] Ready to Merge, [Status] Needs Review

#764 Column Adjustment Pro feature dependency
  includes/admin/class-evf-admin-entries-table-list.php
Labels: Enhancement

#771 Fix - Ajax submission redirect not working
  includes/class-evf-form-task.php
Labels: bug

#772 Fix - Radio Checkbox customization issue with image
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-radio.php
Labels: bug
