Repository wpeverest/everest-forms, pull requests merged in 2021-06, with the labels that each got.

#676 Fix - Success message issue with default form due to redirection.
  changelog.txt
  includes/class-evf-smart-tags.php
  includes/templates/contact.php
Labels: [Status] Ready to Merge

#663 Fix - Default value missing in form fields
  changelog.txt
  includes/fields/class-evf-field-first-name.php
  includes/fields/class-evf-field-last-name.php
  includes/fields/class-evf-field-url.php
Labels: Enhancement, [Status] Ready to Merge

#683 Fix - Ajax Form Submission Smart Tag Not Working
  changelog.txt
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#681 Enhancement - Row Clone Option Added
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-ajax.php
Labels: Enhancement, [Status] Ready to Merge

#682 Fix - Format Email Message Content for Choices Images and Files uploads
  changelog.txt
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#675 Notification option set to individual connections
  assets/js/admin/evf-admin-email.js
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-form-task.php
Labels: Improved-pr, [Status] Ready to Merge

#670 [Feature] - Introduce EVF specific capabilities
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin-menus.php
  includes/admin/class-evf-admin-welcome.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/class-evf-deprecated-filter-hooks.php
  includes/class-evf-form-handler.php
  includes/class-evf-install.php
  includes/class-evf-post-types.php
  includes/class-evf-template-loader.php
  includes/evf-core-functions.php
  includes/evf-entry-functions.php
  includes/evf-update-functions.php
Labels: Enhancement, Improved-pr, [Status] Ready to Merge

#662 Enhancement - Required Indicators for Field Types
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Ready to Merge

#664 Fix - Delete uploaded files after removing Forms or Entries
  changelog.txt
  includes/admin/class-evf-admin-entries.php
  includes/admin/class-evf-admin-forms.php
Labels: [Status] Ready to Merge, bug

#674 Fix - Format Email Message Content For Signature
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-emails.php
Labels: [Status] Ready to Merge, bug

#673 Enhancement - Drop-down date option added
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/select2.css
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement, [Status] Ready to Merge

#653 Fixed - Password Validation logic added
  assets/js/admin/form-builder.js
  changelog.txt
Labels: Enhancement, [Status] Ready to Merge

#688 Tweak - Review notice
  assets/css/activation.css
  assets/css/activation.scss
  includes/admin/views/html-notice-review.php
Labels: Enhancement, [Status] Needs Review

#689 Fix - Permission issue with forms visibility on frontend
  includes/class-evf-form-handler.php
Labels: [Status] Ready to Merge, bug

#690 fix - file uploads capability issue
  changelog.txt
  includes/class-evf-form-handler.php
Labels: [Status] Ready to Merge, bug

#696 Fix - Get entries permission issue
  changelog.txt
  includes/evf-entry-functions.php
Labels: [Status] Ready to Merge, bug

#695 Fix - attach pdf to email glitches
  assets/js/admin/evf-admin-email.js
  changelog.txt
Labels: [Status] Ready to Merge, bug
