Repository wpeverest/everest-forms, pull requests merged in 2021-05, with the labels that each got.

#642 Fix - Signature field display with smart tags
  changelog.txt
  includes/class-evf-emails.php
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#668 Enhancement enable/disable log
  changelog.txt
  includes/admin/settings/class-evf-settings-general.php
  includes/admin/views/html-admin-page-tools.php
  includes/class-evf-logger.php
Labels: Enhancement, [Status] Ready to Merge

#661 Feature - Divider field added
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  changelog.txt
  includes/class-evf-ajax.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-divider.php
Labels: Feature Branch 🚀, [Status] Ready to Merge
