Repository wpeverest/everest-forms, pull requests merged in 2021-03, with the labels that each got.

#604 Fix - Check valid hash and process custom redirection after PayPal Payment
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Ready to Merge, bug

#614 Fix - Welcome page redirection on every plugin updates
  includes/class-evf-install.php
Labels: [Status] Ready to Merge, bug

#615 Fix PayPal standard Redirection Issue
  assets/js/frontend/ajax-submission.js
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Changelog, [Status] Needs Review, bug

#616 Fixed - CSV textarea contents line break issue
  includes/export/class-evf-entry-csv-exporter.php
Labels: [Status] Needs Changelog, [Status] Ready to Merge, bug
