Repository wpeverest/everest-forms, pull requests merged in 2021-07, with the labels that each got.

#705 Cache the form and entries results
  changelog.txt
  includes/class-evf-form-handler.php
  includes/evf-entry-functions.php
Labels: [Status] Ready to Merge, category: performance

#709 Fix - Smart Tag Page Issues
  changelog.txt
  includes/class-evf-form-task.php
  includes/class-evf-smart-tags.php
Labels: [Status] Ready to Merge, bug

#714 Fix - Pagination not working in admin forms list table
  changelog.txt
  includes/admin/class-evf-admin-forms-table-list.php
Labels: [Status] Ready to Merge

#702 Setting Enhancement - Image field added
  assets/js/admin/evf-file-uploader.js
  assets/js/frontend/ajax-submission.js
  changelog.txt
  composer.lock
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  templates/notices/success.php
Labels: [Status] Ready to Merge
