Repository wpeverest/everest-forms, pull requests merged in 2022-04, with the labels that each got.

#888 Fix - Meta Key Translation issue
  changelog.txt
  includes/evf-core-functions.php
Labels: bug, [Status] Needs Changelog

#885 Enhancement - Delete all logs at a time.
  assets/js/admin/tools.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-tools.php
  includes/admin/views/html-admin-page-tools-logs.php
  includes/log-handlers/class-evf-log-handler-file.php
Labels: Enhancement

#886 Fix - Load user filled value in likert field in form submission when error is occurred.
  changelog.txt
  includes/class-evf-form-task.php
Labels: bug

#893 Enhancement - Keyboard shortcut key (Ctrl+h) for showing keyboard shortcut keys in modal.
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs design
