Repository wpeverest/everest-forms, pull requests merged in 2022-07, with the labels that each got.

#909 EVF-338 Feature - Thumb Rating Field.
  assets/js/admin/form-builder.js
  changelog.txt
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-yes-no.php
Labels: Feature Branch 🚀

#946 Enhancement - Zoho CRM listing in add-ons page.
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/zoho.png
  changelog.txt
Labels: Enhancement, [Status] Needs Review

#953 Fix - Auto address field value not rendering issue in style
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
Labels: bug

#954 Dev - Background Image in PDF.
  changelog.txt
  includes/admin/class-evf-admin-settings.php
Labels: Enhancement

#947 Fix - Required issue in multipart/row conditional
  assets/js/admin/form-builder.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-form-task.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-number.php
Labels: [Status] Ready to Merge

#951 Enhancement file uploads in repeater
  assets/js/admin/form-builder.js
  changelog.txt
Labels: bug, [Status] Needs Review
