Repository wpeverest/everest-forms, pull requests merged in 2022-08, with the labels that each got.

#962 Enhancement - multiple select field support
  changelog.txt
  includes/admin/evf-admin-functions.php
  includes/class-evf-ajax.php
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Changelog

#959 Fix - Server-side validation for limit length and minimum length features on single line text and paragraph fields.
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
Labels: bug

#960 Enhancement - Required field validation(global setting, Individual setting)
  assets/js/admin/form-builder.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-first-name.php
  includes/fields/class-evf-field-last-name.php
  includes/fields/class-evf-field-number.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
  includes/fields/class-evf-field-url.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement

#952 Enhancement - PDF global to individual form setting.
  assets/js/admin/evf-file-uploader.js
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-page.php
  includes/admin/evf-admin-functions.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  templates/notices/success.php
Labels: Enhancement, [Status] Needs Review
