Repository wpeverest/everest-forms, pull requests merged in 2022-06, with the labels that each got.

#915 Enhancement - Minimum length feature on the Paragraph/Single Line Text field.
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/frontend/text-limit.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-frontend-scripts.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Changelog

#912 Dependencies for coupons
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr-rtl.css
  assets/css/flatpickr.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/select2-rtl.css
  assets/css/select2.css
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  assets/js/admin/form-builder.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-payment-coupon.php
Labels: [Status] Needs Review, Feature Branch 🚀

#899 Feature - Form field icons.
  assets/js/frontend/ajax-submission.js
  assets/js/frontend/everest-forms.js
  changelog.txt
Labels: [Status] Ready to Merge, [Status] Needs Changelog, Feature Branch 🚀

#889 Export entries with fields and date filter in tools export tab.
  assets/css/admin.scss
  changelog.txt
  includes/admin/class-evf-admin-entries.php
  includes/admin/views/html-admin-page-export.php
  includes/evf-core-functions.php
  includes/export/class-evf-entry-csv-exporter.php
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Changelog

#933 Enhancement - New add-ons listing in add-ons Section.
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/calculations.png
  assets/extensions-json/sections/images/coupons.png
  assets/extensions-json/sections/images/drip.png
  assets/extensions-json/sections/images/frontend-listing.png
  assets/extensions-json/sections/images/hubspot.png
  assets/extensions-json/sections/images/pipedrive.png
  assets/extensions-json/sections/images/razorpay.png
  assets/extensions-json/sections/images/sms-notifications.png
  changelog.txt
Labels: Enhancement

#932 Fix - Prevent more than one Keyboard Shortcut keys pop-up modal opening at a time.
  assets/js/admin/form-builder.js
  changelog.txt
Labels: bug

#929 Enhancement - Pass Field Data to Query String.
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-form-task.php
Labels: Enhancement

#922 Enhancement - Export Selected Entries
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
Labels: Enhancement

#921 Enhancement - Past Date disable
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  changelog.txt
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement

#924 Enhancement - smart tags added
  changelog.txt
  includes/class-evf-smart-tags.php
Labels: Enhancement

#898 Fix - conditional logic field required issue
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-form-task.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-number.php
Labels: [Status] Needs Review, [Status] Needs Changelog

#923 Fix - min/max value glitch and default value validation.
  assets/css/admin.scss
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
Labels: bug, [Status] Needs Review
