Repository wpeverest/everest-forms, pull requests merged in 2022-02, with the labels that each got.

#824 EVF 265 Enhancement - Recaptcha v3 Threshold
  assets/js/admin/settings.js
  changelog.txt
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/class-evf-form-task.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog

#822 EVF-48 Feature - hCaptcha
  assets/js/admin/settings.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, Feature Branch 🚀

#820 Fix - Attribute issue in Multipart
  changelog.txt
  includes/shortcodes/class-evf-shortcode-form.php
Labels: bug, [Status] Needs Review, [Status] Needs Changelog

#786 Enhance - Amp plugin compatibility
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  changelog.txt
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/evf-core-functions.php
  includes/evf-notice-functions.php
  includes/evf-template-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#830 EVF 197 Enhancement - Four column Form
  assets/css/activation.css
  assets/css/admin.css
  assets/css/admin.css.map
  assets/css/admin.scss
  assets/css/everest-forms.css
  assets/css/everest-forms.css.map
  assets/css/everest-forms.scss
  assets/css/flatpickr.css
  assets/css/menu.css
  assets/css/select2.css
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-fields.php
Labels: Enhancement

#823 Feature - Send Test Email
  assets/js/admin/settings.js
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-email.php
  includes/class-evf-ajax.php
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀

#803 Enhance - Form builder validation
  assets/js/admin/admin.js
  changelog.txt
Labels: bug, [Status] Needs Review, [Status] Needs Changelog

#802 EVF-249 Fix - Ajax form submission issue
  assets/js/frontend/ajax-submission.js
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
Labels: bug, [Status] Needs Review, [Status] Needs Changelog

#821 Enhancement - Logger
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
Labels: Enhancement

#787 EVF-230 Fix - WP nonce issue with multiple form on same page
  changelog.txt
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: bug, [Status] Ready to Merge, [Status] Needs Changelog

#825 Feature - Whitelisted Domain
  includes/abstracts/class-evf-form-fields.php
Labels: Feature Branch 🚀

#839 Fix - Ajax Validation error
  assets/js/frontend/ajax-submission.js
Labels: bug

#859 Fix - Preview issue in twenty twenty two theme
  changelog.txt
  includes/class-evf-template-loader.php
Labels: bug

#855 Enhancement - Way to select the fields that go into the PDF
  assets/allowed_tags/allowed_tags.json
  includes/admin/evf-admin-functions.php
  includes/class-evf-ajax.php
  includes/evf-core-functions.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#856 Enhancement - quiz result in email
  assets/js/frontend/ajax-submission.js
  includes/class-evf-form-task.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#854 Fix - reCAPTCHA v3 threshold display issue.
  assets/js/admin/settings.js
  changelog.txt
Labels: Enhancement, [Status] Needs Review

#853 Enhancement - Form Import Success Message
  changelog.txt
  includes/admin/class-evf-admin-import-export.php
Labels: Enhancement, [Status] Needs Review

#852 Enhancement - Ajax Form Submission
  assets/js/frontend/ajax-submission.js
  changelog.txt
  includes/class-evf-form-task.php
Labels: Enhancement, [Status] Needs Review

#847 Enhance - Enable field Drag to another part
  assets/css/admin.scss
  assets/js/admin/form-builder.js
Labels: Enhancement

#838 Enhancement - Range Slider as Payment Slider
  assets/js/admin/form-builder.js
Labels: Enhancement, [Status] Needs Review

#829 Update - Calculation fields support for smart tags
  assets/js/admin/form-builder.js
Labels: Enhancement

#862 EVF-216 Enhancement - Auto fill Address Field
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/select2.css
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement

#837 EVF-268 Feature - WYSIWUG field
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr-rtl.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/select2-rtl.css
  assets/fonts/EverestForms.eot
  assets/fonts/EverestForms.svg
  assets/fonts/EverestForms.ttf
  assets/fonts/EverestForms.woff
  assets/js/frontend/ajax-submission.js
  includes/class-evf-forms-features.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-wysiwyg.php
Labels: [Status] Needs Review, [Status] Needs Changelog, Feature Branch 🚀
