Repository wpeverest/everest-forms, pull requests merged in 2022-05, with the labels that each got.

#908 Enhancement/tooltip
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement, [Status] Ready to Merge

#902 Feature - Keyboard Friendly Forms.
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Review, Feature Branch 🚀

#878 Feature - Validate as Unique
  includes/abstracts/class-evf-form-fields.php
Labels: [Status] Needs Changelog, Feature Branch 🚀

#887 Dev - Compatible with Twilio
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/class-evf-ajax.php
Labels: [Status] Needs Review, Feature Branch 🚀

#900 Dev - Compatible with Razorpay
  assets/js/frontend/ajax-submission.js
  assets/js/frontend/everest-forms.js
Labels: [Status] Needs Review

#884 Enhancement - Export/Import multiple forms at a time.
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/class-evf-admin-import-export.php
  includes/admin/views/html-admin-page-export.php
  includes/admin/views/html-admin-page-import.php
  includes/class-evf-ajax.php
Labels: Enhancement

#916 Fix - Hidden Field default value.
  changelog.txt
  includes/class-evf-smart-tags.php
Labels: bug, [Status] Ready to Merge
