Repository wpeverest/everest-forms, pull requests merged in 2022-11, with the labels that each got.

#1000 Enhancement - Entry ID smart tag in the email message.
  changelog.txt
  includes/class-evf-emails.php
Labels: Enhancement, [Status] Ready to Merge

#999 Fix - Flatpickr date localization not working while the form has more than date one field.
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/fields/class-evf-field-date-time.php
Labels: bug

#976 Dev - Subtotal Field.
  assets/css/menu.scss
  assets/js/admin/form-builder.js
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-payment-subtotal.php
Labels: Feature Branch 🚀

#1007 Enhancement - Set date range x days after or before.
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/fields/class-evf-field-date-time.php
Labels: Enhancement

#973 Dev - Color Field.
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-color.php
Labels: Feature Branch 🚀

#1011 Dev - Stripe refactor compatibility changes.
  assets/js/frontend/ajax-submission.js
  assets/js/frontend/everest-forms.js
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: bug, [Status] Needs Review
