Repository wpeverest/everest-forms, pull requests merged in 2022-03, with the labels that each got.

#875 Tweak - reCAPTCHA text content is changed.
  changelog.txt
  includes/admin/settings/class-evf-settings-recaptcha.php
Labels: [Status] Ready to Merge

#870 Enhancement - reCAPTCHA feature enhanced with reCAPTCHA language.
  changelog.txt
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Enhancement, [Status] Needs Docs, [Status] Needs Changelog

#873 Added toggle case for PDF settings.
  includes/admin/class-evf-admin-settings.php
Labels: Enhancement, [Status] Needs Review

#849 Enhancement - Select All or Unselect All option in Checkboxes and Dropdown(multi-select) field
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-select.php
Labels: Enhancement, [Status] Needs Review

#836 Enhancement - Exclude Some Countries in Country Field
  assets/js/admin/form-builder.js
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement, [Status] Needs Review

#848 Feature - Elementor Widget
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/js/admin/form-builder.min.js
  assets/js/frontend/everest-forms.min.js
  changelog.txt
  includes/class-everest-forms.php
  includes/elementor/class-evf-elementor.php
  includes/elementor/class-evf-widget.php
Labels: Feature Branch 🚀

#874 Feature - Field Visibility
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-first-name.php
  includes/fields/class-evf-field-number.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-textarea.php
  includes/fields/class-evf-field-url.php
Labels: [Status] Needs Review, [Status] Needs Changelog

#863 Enhancement - Builder Optimization
  includes/abstracts/class-evf-form-fields.php
  includes/abstracts/class-evf-settings-api.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/evf-core-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Review, php, category: performance
