Repository wpeverest/everest-forms, pull requests merged in 2022-10, with the labels that each got.

#994 Fix - Send file as Attachment issue.
  assets/js/admin/evf-admin-email.js
Labels: bug, [Status] Needs Review

#986 Refactor - Multiple select2 code in the admin area.
  assets/js/admin/evf-enhanced-select.js
Labels: Enhancement

#993 Fix - Date format not working issue in the Date/Time field.
  assets/css/everest-forms.scss
  changelog.txt
  includes/fields/class-evf-field-date-time.php
Labels: bug

#995 Dev - Compatibility with Conversational Forms
  includes/admin/class-evf-admin-forms-table-list.php
  includes/class-evf-form-handler.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: Approved
