Repository wpeverest/everest-forms, pull requests merged in 2022-12, with the labels that each got.

#1018 Fix - Empty for zero value in the number field.
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-number.php
Labels: bug

#1019 Fix - Entry ID wp error object.
  changelog.txt
  includes/class-evf-emails.php
Labels: bug

#1031 Enhancement - Extra argument email message apply_filters().
  includes/class-evf-emails.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#1017 Fix - CSV export issue with the dropdown field.
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
Labels: bug, [Status] Needs Review
