Repository wpeverest/everest-forms, pull requests merged in 2022-09, with the labels that each got.

#970 Enhancement - New add-ons are listed on the add-ons page.
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/cloud-storage.jpg
  assets/extensions-json/sections/images/constant-contact.jpg
  assets/extensions-json/sections/images/salesforce.jpg
Labels: Enhancement

#972 Enhacnement - Filter added for dropdown options.
  changelog.txt
  includes/fields/class-evf-field-select.php
Labels: Enhancement

#977 Fix - Empty field values in exported CSV file while changing meta key.
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
Labels: bug

#979 Enhancement - Submit form name form by pressing the enter key while adding a new form.
  assets/js/admin/evf-setup.js
  changelog.txt
Labels: Enhancement, [Status] Needs Changelog

#975 Refactor - Multi-select value code in the builder.
  assets/js/admin/form-builder.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
Labels: [Status] Ready to Merge, category: refactor

#974 Dev - Dynamic country wise state dropdown.
  assets/css/admin.scss
  assets/js/admin/evf-enhanced-select.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/evf-core-functions.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#982 Dev - Progress Field.
  changelog.txt
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-progress.php
Labels: Feature Branch 🚀

#978 Feature - Reset Field
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-reset.php
Labels: [Status] Needs Review, [Status] Needs Changelog

#985 Enhancement - New add-ons are listed on the add-ons page.
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/getresponse.jpg
  assets/extensions-json/sections/images/sendinblue.jpg
Labels: Enhancement
