Repository wpeverest/everest-forms, pull requests merged in 2023-06, with the labels that each got.

#1081 Enhancement - Upgrade to pro link
  changelog.txt
  includes/admin/class-evf-admin-menus.php
Labels: Enhancement, [Status] Ready to Merge, Tested

#1085 Dependencies for Authorize.Net
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/admin/upgrade.js
  assets/js/frontend/ajax-submission.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-payment-authorize-net.php
Labels: [Status] Needs Review, Feature Branch 🚀

#1084 Tweak - Form locate option where form is activated
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/class-evf-ajax.php
Labels: Enhancement, [Status] Needs Review

#1114 Evf 497 Feature - Cloudfare Turnstile integration
  assets/js/admin/settings.js
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀, [Status] Needs Test
