Repository wpeverest/everest-forms, pull requests merged in 2023-10, with the labels that each got.

#1156 Fix - Booked Slot not deleting after entry deletion.
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Test

#1161 Enhancement - Form Builder Design.
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/flatpickr.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/select2.css
  assets/css/select2.scss
  assets/css/variables/_colors.scss
  assets/images/enable-email-toggle.png
  assets/images/everest-forms-logo.png
  assets/images/icons/evf-pro-icon.png
  assets/js/admin/evf-admin-email.js
  assets/js/admin/evf-admin-email.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/evf-admin-functions.php
  includes/admin/views/html-admin-page-builder.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1170 EVF-815 Fix - Issue with downloading AI Contact Form Addon
  includes/admin/views/html-admin-page-addons.php
Labels: bug, Tested, Approved
