Repository wpeverest/everest-forms, pull requests merged in 2023-01, with the labels that each got.

#1046 Enhancement - CSV export for repeater field.
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
Labels: bug

#1045 Fix - Stripe issue with credit card field empty.
  assets/js/frontend/ajax-submission.js
  changelog.txt
Labels: bug

#1047 Enahcement - Field validation in Builder.
  assets/js/admin/form-builder.js
Labels: bug

#1042 Dev - Whitelist domain.
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement

#1048 Fix - EVF Tooltip issue with WooCommerce orders table
  assets/js/jquery-tiptip/jquery.tipTip.js
  assets/js/jquery-tiptip/jquery.tipTip.min.js
Labels: bug, [Status] Needs Review, [Status] Needs Changelog

#1049 Feature - Usage tracking implementation.
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-misc.php
  includes/class-everest-forms.php
  includes/class-evf-cron.php
  includes/stats/class-evf-stats.php
  uninstall.php
Labels: Feature Branch 🚀

#1050 Feature - Deactivation popup.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/deactivation-feedback.scss
  assets/js/admin/deactivation-feedback.js
  assets/js/admin/plugins.js
  assets/js/admin/plugins.min.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-deactivation-feedback.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-deactivation-popup.php
  includes/class-evf-ajax.php
Labels: Feature Branch 🚀

#1052 Feature - Allow usage tracking notice.
  assets/css/activation.scss
  includes/admin/class-evf-admin-notices.php
  includes/admin/settings/class-evf-settings-misc.php
  includes/admin/views/html-notice-allow-usage.php
  includes/class-evf-ajax.php
Labels: Feature Branch 🚀
