Repository wpeverest/everest-forms, pull requests merged in 2023-03, with the labels that each got.

#1060 Fix - Payment checkbox smart tag value is not showing email.
  changelog.txt
  includes/class-evf-smart-tags.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Changelog

#1068 Fix - Undefined array key 'datetime_style' issue
  includes/fields/class-evf-field-date-time.php
Labels: bug, [Status] Ready to Merge

#1067 Fix - Undefined index and array to string conversion issue.
  includes/class-evf-emails.php
Labels: bug, [Status] Ready to Merge

#1063 Tweak - Choose File translation issue in the import forms
  includes/admin/views/html-admin-page-import.php
Labels: [Status] Ready to Merge

#1062 Fix - Send Test Email To option does not display the value saved value in the DB
  includes/admin/settings/class-evf-settings-email.php
Labels: bug, [Status] Ready to Merge

#1061 Fix - String length mismatch for non-English characters in the Limit Length feature
  includes/abstracts/class-evf-form-fields.php
Labels: bug, [Status] Ready to Merge

#1073 Refactor - Form Templates.
  assets/css/admin.css
  assets/css/admin.scss
  assets/extensions-json/templates/all_templates.json
  assets/extensions-json/templates/images/Advanced Contact Form.png
  assets/extensions-json/templates/images/Donation Form.png
  assets/extensions-json/templates/images/Job Vacancy Form.png
  assets/extensions-json/templates/images/Survey Form.png
  assets/extensions-json/templates/images/advanced-contact-form.png
  assets/extensions-json/templates/images/design-agency-request-a-quote.png
  assets/extensions-json/templates/images/donation-form.png
  assets/extensions-json/templates/images/ebook-form.png
  assets/extensions-json/templates/images/hotel-booking.png
  assets/extensions-json/templates/images/job-vacancy-form.jpg
  assets/extensions-json/templates/images/leave-request-form.png
  assets/extensions-json/templates/images/medical-appointment-form.png
  assets/extensions-json/templates/images/modeling-application-form.jpg
  assets/extensions-json/templates/images/new-form.png
  assets/extensions-json/templates/images/restaurant-table-booking.png
  assets/extensions-json/templates/images/simple-contact-form.png
  assets/extensions-json/templates/images/simple-registration.png
  assets/extensions-json/templates/images/simple-support-form.png
  assets/extensions-json/templates/images/style-customizer.png
  assets/extensions-json/templates/images/survey-form.png
  assets/extensions-json/templates/template_sections.json
  assets/js/admin/form-template-controller.js
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-form-templates.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-admin-page-form-templates.php
  includes/class-evf-ajax.php
  includes/class-evf-form-handler.php
Labels: Enhancement, [Status] Needs Review
