Repository wpeverest/everest-forms, pull requests merged in 2023-08, with the labels that each got.

#1146 Dev - Compatibility for stripe redirection issue.
  assets/js/frontend/ajax-submission.js
Labels: bug

#1144 Dev - Filter added for checkbox and radio options.
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1145 Fix - Accepting Numbers Below 0 Despite Minimum Limit of 0.
  changelog.txt
  includes/fields/class-evf-field-number.php
Labels: bug

#1143 Fix - Hide empty fields in the email.
  changelog.txt
  includes/class-evf-emails.php
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1138 Enhance - Option to load fonts locally
  changelog.txt
  includes/admin/settings/class-evf-settings-misc.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/evf-core-functions.php
  includes/libraries/wptt-webfont-loader.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Test

#1151 #781 Tweak - Change URL with new website URL
  .github/CONTRIBUTING.md
  README.md
  assets/extensions-json/sections/all_extensions.json
  composer.json
  everest-forms.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-menus.php
  includes/admin/class-evf-admin-welcome.php
  includes/admin/settings/class-evf-settings-misc.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/admin/views/html-admin-page-addons.php
  includes/admin/views/html-notice-allow-usage.php
  includes/admin/views/html-notice-review.php
  includes/class-evf-install.php
  includes/fields/class-evf-field-text.php
  readme.txt
  templates/emails/body-default.php
  templates/emails/default.php
  templates/emails/field-default.php
  templates/emails/footer-default.php
  templates/emails/header-default.php
  templates/notices/error.php
  templates/notices/notice.php
  templates/notices/success.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1131 Tweak - Remove rating request notification
  changelog.txt
  includes/admin/class-evf-admin.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1148 Feature - Lookup field
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-lookup.php
  readme.txt
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀, [Status] Needs Test
