Repository wpeverest/everest-forms, pull requests merged in 2023-11, with the labels that each got.

#1176 Fix - Sanitization issue.
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  readme.txt
Labels: [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1171 Fix - PDF download issue after form submission for individual settings.
  includes/class-evf-form-task.php
Labels: bug

#1178 Tweak - Compatibility with newly introduced ThemeGrill Agency Plan.
  assets/extensions-json/sections/all_extensions.json
  assets/js/admin/evf-setup.js
  changelog.txt
  everest-forms.php
  includes/admin/class-evf-admin-addons.php
  includes/admin/class-evf-admin.php
  includes/admin/views/html-admin-page-addons.php
  includes/admin/views/html-admin-page-form-templates.php
  includes/class-everest-forms.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-captcha.php
  includes/fields/class-evf-field-credit-card.php
  includes/fields/class-evf-field-likert.php
  includes/fields/class-evf-field-payment-authorize-net.php
  includes/fields/class-evf-field-payment-coupon.php
  includes/fields/class-evf-field-repeater.php
  includes/fields/class-evf-field-scale-rating.php
  includes/fields/class-evf-field-yes-no.php
  package-lock.json
  package.json
  readme.txt
Labels: Enhancement, Tested, Approved
