Repository wpeverest/everest-forms, pull requests merged in 2023-05, with the labels that each got.

#1097 Tweak - Send CSV in email
  assets/js/admin/evf-admin-email.js
  changelog.txt
  includes/class-evf-form-task.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1096 Fix - Repeater field issue when exporting the CSV.
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1094 Fix - Unnecessary JS Load on Frontend.
  changelog.txt
  includes/class-evf-frontend-scripts.php
  includes/evf-core-functions.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1092 Fix - CSV export issue.
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1091 Fix - Form not showing to export the form while storing entry information is disabled
  changelog.txt
  includes/admin/views/html-admin-page-export.php
  includes/evf-core-functions.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1090 Fix - Smart tag {first_name} {last_name} are not working.
  changelog.txt
  includes/class-evf-smart-tags.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1088 Fix - Error when enabling image choices without uploading image in checkbox.
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1087 Enhancement - Next Previous link on single entry view admin page
  assets/css/admin.scss
  changelog.txt
  includes/admin/views/html-admin-page-entries-view.php
  includes/evf-entry-functions.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1086 Enhancement - Timezone selection for DateTime field
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1083 Fix - Payment status is not showing in CSV
  changelog.txt
  includes/export/class-evf-entry-csv-exporter.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1089 Fix - Minimum word count error message issue
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/class-evf-frontend-scripts.php
  readme.txt
Labels: bug, [Status] Needs Changelog

#1095 Feature - Everest forms on top admin menu bar
  changelog.txt
  includes/admin/class-evf-admin-menus.php
  readme.txt
Labels: [Status] Ready to Merge, Feature Branch 🚀

#1100 Enhancement - Anti Spam Setting.
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1082 Enhancement - Search forms in entries select.
  assets/js/admin/evf-enhanced-select.js
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog

#1101 Fix- PDF download link not showing issue with paypal.
  changelog.txt
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: bug, [Status] Ready to Merge
