Repository wpeverest/everest-forms, pull requests merged in 2023-12, with the labels that each got.

#1182 Fix - PayPal redirection issue when Stripe and PayPal both is enabled.
  assets/js/frontend/ajax-submission.js
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1185 Fix- Empty Values in Entries for (Select, Checkbox, Radio) Fields when WordPress Site is in Another Language.
  changelog.txt
  includes/evf-core-functions.php
  readme.txt
Labels: bug

#1179 Feature - Akismet integration
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/class-evf-form-task.php
  includes/evf-core-functions.php
  includes/evf-entry-functions.php
  readme.txt
Labels: Feature Branch 🚀

#1192 Fix - PHP 8.2 dynamic properties are deprecated.
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/class-everest-forms.php
  readme.txt
Labels: bug, [Status] Needs Changelog, [Status] Needs Test
