Repository wpeverest/everest-forms, pull requests merged in 2024-02, with the labels that each got.

#1221 Fix - Fatal error in entries function.
  includes/evf-entry-functions.php
Labels: bug

#1189 Enhancement - Screenshot video on upgrade to pro popup
  assets/js/admin/form-builder.js
  assets/js/admin/upgrade.js
  changelog.txt
  everest-forms.php
  includes/abstracts/class-evf-form-fields.php
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/class-everest-forms.php
  includes/fields/class-evf-field-address.php
  includes/fields/class-evf-field-captcha.php
  includes/fields/class-evf-field-color.php
  includes/fields/class-evf-field-country.php
  includes/fields/class-evf-field-credit-card.php
  includes/fields/class-evf-field-divider.php
  includes/fields/class-evf-field-file-upload.php
  includes/fields/class-evf-field-hidden.php
  includes/fields/class-evf-field-html.php
  includes/fields/class-evf-field-image-upload.php
  includes/fields/class-evf-field-likert.php
  includes/fields/class-evf-field-lookup.php
  includes/fields/class-evf-field-password.php
  includes/fields/class-evf-field-payment-authorize-net.php
  includes/fields/class-evf-field-payment-checkbox.php
  includes/fields/class-evf-field-payment-coupon.php
  includes/fields/class-evf-field-payment-quantity.php
  includes/fields/class-evf-field-payment-radio.php
  includes/fields/class-evf-field-payment-single.php
  includes/fields/class-evf-field-payment-subtotal.php
  includes/fields/class-evf-field-payment-total.php
  includes/fields/class-evf-field-phone.php
  includes/fields/class-evf-field-privacy-policy.php
  includes/fields/class-evf-field-progress.php
  includes/fields/class-evf-field-range-slider.php
  includes/fields/class-evf-field-rating.php
  includes/fields/class-evf-field-repeater.php
  includes/fields/class-evf-field-reset.php
  includes/fields/class-evf-field-scale-rating.php
  includes/fields/class-evf-field-signature.php
  includes/fields/class-evf-field-title.php
  includes/fields/class-evf-field-wysiwyg.php
  includes/fields/class-evf-field-yes-no.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1188 Tweak - Clone or duplicate core form settings email
  assets/js/admin/admin.js
  assets/js/admin/evf-admin-email.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-ajax.php
  readme.txt
Labels: Enhancement

#1193 Feature - Email preview
  assets/js/admin/evf-admin-email.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-ajax.php
  includes/class-evf-template-loader.php
  includes/evf-core-functions.php
  readme.txt
  templates/emails/body-default.php
  templates/emails/email-preview.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Test

#1219 Fix - Show Values Setting Not Displaying in Select Field.
  changelog.txt
  includes/fields/class-evf-field-select.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Test

#1220 Fix - Everest Forms query running in every pages.
  changelog.txt
  includes/evf-core-functions.php
  includes/evf-entry-functions.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1203 Feature - Google calendar integration for appointment scheduling
  assets/js/admin/form-builder.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: Feature Branch 🚀
