Repository wpeverest/everest-forms, pull requests merged in 2024-07, with the labels that each got.

#1266 Feature - Import entries in our form using csv
  assets/css/admin.scss
  assets/js/admin/tool-import-entries.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/form-migrator/abstract-evf-form-migrator.php
  includes/admin/views/html-admin-page-import.php
  includes/class-evf-ajax.php
  includes/class-evf-background-process-import-entries.php
Labels: Enhancement

#1271 Enhance - Dashboard page
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  dist/blocks.min.js
  dist/dashboard.min.js
  dist/dashboard.min.js.LICENSE.txt
  dist/reactPlayerPreview.min.js
  includes/RestApi/controllers/version1/class-evf-modules.php
  package-lock.json
  package.json
  src/dashboard/components/Header/Header.js
  src/dashboard/screens/Help/Lists/ShortcodesLists/ShortcodesLists.js
  src/dashboard/screens/Modules/Modules.js
  src/dashboard/screens/Modules/components/ModuleBody.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  src/dashboard/screens/Modules/components/modules-api.js
Labels: Enhancement

#1286 Fix - Post Meta Smart tag not working.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/everest-forms-rtl.css
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/extensions-json/sections/all_extensions.json
  assets/images/icons/premium-list-check-icon.svg
  assets/images/settings-icons/geolocation.svg
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/admin/settings.js
  assets/js/admin/settings.min.js
  assets/js/admin/tool-import-entries.js
  assets/js/admin/tool-import-entries.min.js
  assets/js/admin/upgrade.js
  assets/js/admin/upgrade.min.js
  assets/js/frontend/everest-forms.js
  assets/js/frontend/everest-forms.min.js
  changelog.txt
  dist/blocks.min.js
  dist/dashboard.min.js
  dist/dashboard.min.js.LICENSE.txt
  dist/form-selector/block.json
  dist/frontend-listing/block.json
  dist/reactPlayerPreview.min.js
  dist/user-login/block.json
  everest-forms.php
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/abstracts/class-evf-form-fields-upload.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/form-migrator/abstract-evf-form-migrator.php
  includes/admin/settings/class-evf-settings-email.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/admin/settings/class-evf-settings-reporting.php
  includes/admin/views/html-admin-page-import.php
  includes/admin/views/html-admin-settings.php
  includes/blocks/class-evf-blocks.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/class-evf-background-process-import-entries.php
  includes/class-evf-emails.php
  includes/class-evf-frontend-scripts.php
  includes/class-evf-smart-tags.php
  includes/evf-core-functions.php
  package-lock.json
  package.json
  readme.txt
  src/blocks/blocks/form-selector/block.json
  src/blocks/blocks/frontend-listing/block.json
  src/blocks/blocks/user-login/block.json
  src/dashboard/components/Header/Header.js
  src/dashboard/screens/Help/Lists/ShortcodesLists/ShortcodesLists.js
  src/dashboard/screens/Modules/Modules.js
  src/dashboard/screens/Modules/components/ModuleBody.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  src/dashboard/screens/Modules/components/modules-api.js
  webpack.config.js
Labels: bug

#1285 Fix - Duplicate entries showing in entry preview.
  includes/admin/class-evf-admin-preview-confirmation.php
Labels: bug

#1265 Tweak - Enable minimum time for form submission
  assets/js/admin/form-builder.js
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/evf-admin-functions.php
  includes/class-evf-form-task.php
  includes/class-evf-frontend-scripts.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: Enhancement

#1289 Feature - Brevo module compatibility
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/brevo.webp
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1295 Dev - Drip Compatibility
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, [Status] Needs Docs, [Status] Needs Changelog

#1292 Dev - Transaction Table
  changelog.txt
  includes/admin/views/html-admin-page-tools.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, Feature Branch 🚀, [Status] Needs Test

#1297 Dev - ConvertKit Compatibility
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/convertkit.png
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1294 Dev - GetResponse compatibility
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test
