Repository wpeverest/everest-forms, pull requests merged in 2024-06, with the labels that each got.

#1281 Enhancement - Global Setting Premium Sidebar.
  assets/css/admin.scss
  assets/images/icons/premium-list-check-icon.svg
  assets/images/settings-icons/geolocation.svg
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/views/html-admin-settings.php
Labels: Enhancement

#1279 Fix - Block design all messed up when viewed in block editor.
  assets/css/everest-forms.scss
  changelog.txt
  dist/form-selector/block.json
  dist/frontend-listing/block.json
  dist/user-login/block.json
  includes/blocks/class-evf-blocks.php
  src/blocks/blocks/form-selector/block.json
  src/blocks/blocks/frontend-listing/block.json
  src/blocks/blocks/user-login/block.json
Labels: bug

#1280 Tweak - Test email input and button design
  assets/css/admin.scss
  assets/js/admin/settings.js
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-email.php
  includes/admin/settings/class-evf-settings-reporting.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1278 Fix - Wrong instruction on captcha
  changelog.txt
  includes/admin/class-evf-admin-assets.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1275 Fix - Email template on email clone, save and continue forms
  changelog.txt
  includes/class-evf-ajax.php
  includes/class-evf-emails.php
Labels: bug
