Repository wpeverest/everest-forms, pull requests merged in 2024-03, with the labels that each got.

#1229 Fix - Restrict font_url for unauthorized users and allow only certain font_url.
  changelog.txt
  includes/class-evf-ajax.php
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1231 Feature - Add Search functionality on Addons page
  assets/css/admin.scss
  assets/css/everest-forms.css
  assets/css/everest-forms.scss
  assets/images/icons/embed-back-icon.svg
  assets/images/icons/red-arrow.svg
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  assets/js/admin/gutenberg/shortcode-form-embed.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-embed-wizard.php
  includes/admin/views/html-admin-page-addons.php
  includes/admin/views/html-admin-page-builder.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/class-evf-form-block.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1225 Feature - Form migrator for wpforms
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/tools.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-forms.php
  includes/admin/class-evf-admin-tools.php
  includes/admin/class-evf-admin.php
  includes/admin/form-migrator/abstract-evf-form-migrator.php
  includes/admin/form-migrator/class-evf-fm-contactform7.php
  includes/admin/form-migrator/class-evf-fm-wpforms.php
  includes/admin/views/html-admin-page-form-migrator.php
  includes/admin/views/html-admin-page-tools.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀, [Status] Needs Test

#1224 Feature - System Information
  assets/css/admin.scss
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/class-evf-admin-tools.php
  includes/admin/views/html-admin-page-setting.php
  includes/admin/views/html-admin-page-tools.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1241 Tweak - Filter added for template hierarchy.
  changelog.txt
  includes/class-evf-template-loader.php
  readme.txt
Labels: Enhancement, [Status] Needs Changelog

#1218 Enhancement - Date Field Formats
  changelog.txt
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1217 Enhancement - Appended active class to active input field
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1213 Tweak - Enhance AI contact form setting options
  assets/js/admin/form-builder.js
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test
