Repository wpeverest/everest-forms, pull requests merged in 2024-05, with the labels that each got.

#1258 Fix - Custom JS issue with html special character.
  includes/shortcodes/class-evf-shortcode-form.php
Labels: bug, Tested, Approved

#1255 Enhancement - Gutenberg block
  assets/js/admin/gutenberg/form-block.js
  assets/js/admin/gutenberg/form-block.min.js
  assets/js/admin/gutenberg/shortcode-form-embed.js
  includes/RestApi/class-evf-rest-api.php
  includes/RestApi/controllers/version1/class-evf-gutenberg-blocks.php
  includes/blocks/block-types/class-evf-blocks-abstract.php
  includes/blocks/block-types/class-evf-blocks-form-selector.php
  includes/blocks/block-types/class-evf-blocks-frontend-listing.php
  includes/blocks/block-types/class-evf-blocks-user-login.php
  includes/blocks/class-evf-blocks.php
  includes/class-everest-forms.php
  includes/class-evf-form-block.php
  package.json
  src/blocks/blocks/form-selector/Edit.js
  src/blocks/blocks/form-selector/Save.js
  src/blocks/blocks/form-selector/block.json
  src/blocks/blocks/form-selector/index.js
  src/blocks/blocks/frontend-listing/Edit.js
  src/blocks/blocks/frontend-listing/Save.js
  src/blocks/blocks/frontend-listing/block.json
  src/blocks/blocks/frontend-listing/index.js
  src/blocks/blocks/index.js
  src/blocks/blocks/user-login/Edit.js
  src/blocks/blocks/user-login/Save.js
  src/blocks/blocks/user-login/block.json
  src/blocks/blocks/user-login/index.js
  src/blocks/components/Icon.js
  src/blocks/index.js
  webpack.config.js
Labels: Enhancement, [Status] Needs Docs, Tested, Approved

#1259 Enhancement - Global Setting Design.
  assets/css/admin.scss
  assets/images/icons/collapse-line.svg
  assets/images/icons/evf-global-settings-logo.png
  assets/images/icons/send-icon.svg
  assets/images/icons/upload-icon.svg
  assets/images/integration-image/convertkit.png
  assets/images/integration-image/dropbox.png
  assets/images/integration-image/google-drive.png
  assets/images/integration-image/google-sheets.png
  assets/images/integration-image/mailchimp.png
  assets/images/settings-icons/analytics.svg
  assets/images/settings-icons/email.svg
  assets/images/settings-icons/general.svg
  assets/images/settings-icons/geolocation.svg
  assets/images/settings-icons/integration.svg
  assets/images/settings-icons/misc.svg
  assets/images/settings-icons/payment.svg
  assets/images/settings-icons/pdf-submission.svg
  assets/images/settings-icons/recaptcha.svg
  assets/images/settings-icons/validation.svg
  assets/js/admin/settings.js
  assets/js/admin/upgrade.js
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-email.php
  includes/admin/settings/class-evf-settings-general.php
  includes/admin/settings/class-evf-settings-integrations.php
  includes/admin/settings/class-evf-settings-misc.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  includes/admin/views/html-admin-settings.php
  includes/class-evf-integrations.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1253 Enhancement - Captcha field.
  assets/css/admin.scss
  assets/js/admin/upgrade.js
  includes/admin/builder/class-evf-builder-fields.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-ajax.php
  includes/class-evf-fields.php
  includes/class-evf-form-task.php
  includes/fields/class-evf-field-hcaptcha.php
  includes/fields/class-evf-field-recaptcha.php
  includes/fields/class-evf-field-turnstile.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test
