Repository wpeverest/everest-forms, pull requests merged in 2024-08, with the labels that each got.

#1296 Feature - Salesflare into Module
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/Salesflare.webp
  changelog.txt
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1301 Feature - Delete option in Header logo in PDF Submission
  assets/css/admin.scss
  assets/js/admin/evf-file-uploader.js
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  readme.txt
Labels: Enhancement, [Status] Needs Review

#1306 Feature - Telegram integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/telegram.webp
  changelog.txt
  includes/admin/builder/class-evf-builder-page.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/evf-core-functions.php
  readme.txt
Labels: [Status] Ready to Merge, Feature Branch 🚀

#1307 Enhancement - Custom file name settings
  changelog.txt
  includes/abstracts/class-evf-form-fields-upload.php
  includes/fields/class-evf-field-file-upload.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1305 Dev - Constant contact and PipeDrive compatibility
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1293 Dev- Square Payment Gateway
  assets/css/admin.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/square-payment.png
  assets/js/admin/evf-setup.js
  assets/js/admin/form-builder.js
  assets/js/admin/upgrade.js
  assets/js/frontend/ajax-submission.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-form-task.php
  includes/class-evf-forms-features.php
  includes/fields/class-evf-field-payment-square.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: Enhancement

#1302 Dev - Airtable Compatibility
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/Airtable.png
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1300 Feature - Mollie payment integration
  assets/css/admin.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/mollie.webp
  assets/js/admin/upgrade.js
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-frontend-scripts.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test
