Repository wpeverest/everest-forms, pull requests merged in 2024-04, with the labels that each got.

#1238 Feature - Show entry preview after form submission
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.js
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-preview-confirmation.php
  includes/class-everest-forms.php
  includes/class-evf-form-task.php
  readme.txt
  templates/notices/preview.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1234 Feature - Admin approval entries
  assets/css/admin.scss
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-evf-form-task.php
  includes/evf-entry-functions.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1228 Feature - Email scheduling in daily, weekly or monthly for the progress data of form
  assets/images/Everest-forms-horizontal-Logo.png
  assets/images/evf-white-bg-logo.png
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-evf-admin-settings.php
  includes/admin/class-evf-admin.php
  includes/admin/settings/class-evf-settings-reporting.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/class-evf-cron.php
  includes/class-evf-emails.php
  includes/class-evf-report-cron.php
  includes/class-evf-reporting.php
  includes/evf-core-functions.php
  templates/emails/summary-email-body-default.php
  templates/emails/summary-email-footer-default.php
  templates/emails/summary-email-header-default.php
Labels: [Status] Needs Review, [Status] Needs Docs, [Status] Needs design, Feature Branch 🚀, [Status] Needs Test
