Repository wpeverest/everest-forms, pull requests merged in 2024-09, with the labels that each got.

#1327 Tweak - Hidden field editable compatibility
  includes/evf-core-functions.php
  includes/fields/class-evf-field-hidden.php
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Changelog

#1316 Tweak - Catch mail send error
  changelog.txt
  includes/admin/class-evf-admin-notices.php
  includes/admin/views/html-notice-email-failed-notice.php
  includes/class-evf-ajax.php
  includes/class-evf-emails.php
  includes/evf-core-functions.php
  readme.txt
Labels: Enhancement

#1322 Feature - Entry submission RestApi
  assets/css/admin.scss
  assets/js/admin/admin.js
  includes/RestApi/class-evf-rest-api.php
  includes/RestApi/controllers/version1/class-evf-entry-submission.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-misc.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/evf-core-functions.php
Labels: [Status] Ready to Merge, Feature Branch 🚀

#1328 Fix - Global Setting Premium Sidebar Design Issue.
  assets/css/admin.scss
  assets/js/admin/admin.js
  changelog.txt
  includes/evf-core-functions.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1317 Dev - Feature api log table
  assets/css/admin.scss
  includes/admin/views/html-admin-page-tools.php
Labels: [Status] Needs Docs, dependencies, Merged

#1326 Enhancement - Send file directly as an attachment.
  includes/abstracts/class-evf-form-fields-upload.php
  includes/class-evf-emails.php
Labels: Enhancement, [Status] Ready to Merge

#1318 Dev - Aweber integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/aweber.webp
  changelog.txt
  readme.txt
Labels: Feature Branch 🚀

#1321 Dev- Calculation Module
  assets/css/code-mirror/show-hint.min.css
  assets/extensions-json/sections/all_extensions.json
  assets/js/admin/form-builder.js
  assets/js/code-mirror/show-hint.js
  assets/js/code-mirror/show-hint.min.js
  changelog.txt
  includes/admin/class-evf-admin-assets.php
  includes/class-evf-ajax.php
  includes/evf-core-functions.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1332 Fix - Format likert field data in seperate column wise while exporting entry
  includes/export/class-evf-entry-csv-exporter.php
Labels: bug, Approved, Merged
