Repository wpeverest/everest-forms, pull requests merged in 2024-11, with the labels that each got.

#1368 Fix - Focus on last error message on form validation
  assets/js/frontend/everest-forms.js
Labels: bug, [Status] Ready to Merge

#1349 Feature - Oxygen builder integration
  addons/Addons.php
  addons/OxygenBuilder/Helper.php
  addons/OxygenBuilder/OxygenBuilder.php
  addons/OxygenBuilder/OxygenElement.php
  addons/OxygenBuilder/OxygenFormWidget.php
  assets/extensions-json/sections/all_extensions.json
  assets/js/frontend/everest-forms.js
  changelog.txt
  composer.json
  composer.lock
  everest-forms.php
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
  includes/evf-core-functions.php
  readme.txt
  src/dashboard/Constants/Products.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  traits/Singleton.php
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀, [Status] Needs Test

#1352 Fix - Tooltips doesnot work on mobile
  assets/js/admin/admin.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1343 Dev - Slack Integration Module
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/Slack.png
  changelog.txt
  includes/evf-core-functions.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1355 Feature - Bricks Builder Comaptibility
  addons/Addons.php
  addons/BricksBuilder/BricksBuilder.php
  addons/BricksBuilder/BricksFormWidget.php
  addons/BricksBuilder/Helper.php
  addons/OxygenBuilder/Helper.php
  addons/OxygenBuilder/OxygenBuilder.php
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/bricks-builder.png
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  readme.txt
  src/dashboard/Constants/Products.js
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1348 Fix - Double render of overall feedbak in quiz reporting
  includes/class-evf-form-task.php
Labels: bug, [Status] Ready to Merge

#1358 Feature - Divi Builder Compatibility
  .gitignore
  addons/Addons.php
  addons/DiviBuilder/DiviBuilder.php
  addons/DiviBuilder/EverestFormsModule.php
  addons/DiviBuilder/Helper.php
  addons/OxygenBuilder/OxygenBuilder.php
  assets/css/everest-forms.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/divi.png
  assets/images/icons/Everest-forms-vertical Logo.svg
  changelog.txt
  dist/dashboard.min.js
  includes/RestApi/controllers/version1/class-evf-modules.php
  readme.txt
  src/dashboard/Constants/Products.js
  src/divibuilder/App.jsx
  src/divibuilder/DiviBuilder.jsx
  src/divibuilder/index.jsx
  src/divibuilder/modules/EverestFormsModule.jsx
  webpack.config.js
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1353 Feature - Beaver Builder Compatibility
  addons/Addons.php
  addons/BeaverBuilder/BeaverBuilder.php
  addons/BeaverBuilder/EverestFormModule.php
  addons/BeaverBuilder/Helper.php
  addons/BeaverBuilder/includes/frontend.php
  addons/DiviBuilder/DiviBuilder.php
  addons/DiviBuilder/EverestFormsModule.php
  addons/DiviBuilder/Helper.php
  addons/OxygenBuilder/OxygenElement.php
  assets/css/everest-forms.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/beaver builder.png
  assets/extensions-json/sections/images/beaver-builder.png
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  readme.txt
  src/dashboard/Constants/Products.js
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1366 Fix - Background color for PDF submission
  changelog.txt
  includes/evf-core-functions.php
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Test

#1335 Tweak - Move active campaign to module
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1340 Dev - Get gist integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/getgist.png
  changelog.txt
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1363 Dev - User Registration Social Login
  assets/extensions-json/sections/all_extensions.json
  assets/images/settings-icons/user_registration.svg
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1336 Tweak - Moved Campaign Monitor to module
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1354 Dev - CleverReach Integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/cleverreach.png
  changelog.txt
  readme.txt
Labels: [Status] Needs Review, [Status] Needs Docs, [Status] Needs design, Feature Branch 🚀, [Status] Needs Test

#1341 Tweak - Coupon into module
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  includes/fields/class-evf-field-payment-coupon.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1346 Feature - License settings page
  assets/images/settings-icons/license.svg
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  includes/admin/views/html-admin-settings.php
  readme.txt
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1350 Feature - WPBakery Builder Compatibility
  addons/Addons.php
  addons/WPBakeryBuilder/Helper.php
  addons/WPBakeryBuilder/WPBakeryBuilder.php
  assets/css/everest-forms.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/wpbakery.png
  assets/images/icons/Everest-forms-verticalLogolight.svg
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
  src/dashboard/Constants/Products.js
Labels: [Status] Needs Review, Feature Branch 🚀, [Status] Needs Test

#1362 Dev - SMS Notification into module
  assets/extensions-json/sections/all_extensions.json
Labels: Enhancement, [Status] Needs Review, [Status] Needs Test

#1342 Dev - amoCRM Module
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/amoCRM.png
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, Feature Branch 🚀, Approved

#1364 Fix - Critical issue when the publishable key is empty in live mode for recurring payment
  assets/js/admin/upgrade.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Needs Review, [Status] Needs Test
