Repository wpeverest/everest-forms, pull requests merged in 2025-06, with the labels that each got.

#1442 Enhance - Form builder design
  assets/css/admin.scss
  includes/admin/views/html-admin-page-builder.php
Labels: Enhancement, [Status] Ready to Merge, Approved

#1455 Enhance- Prevent form save if the field is empty.
  includes/class-evf-ajax.php
Labels: Enhancement, Approved, Merged

#1457 Fix - jQuery validation v1.19.2 is flagged as vulnerable
  assets/js/jquery-validate/jquery.validate.js
  assets/js/jquery-validate/jquery.validate.min.js
  includes/class-evf-frontend-scripts.php
Labels: bug, [Status] Needs Review, [Status] Needs Test

#1459 Fix - Inconsistency on form builder field option design
  assets/js/admin/form-builder.js
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1458 Fix - Module activation design in dashboard
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  readme.txt
  src/dashboard/screens/Modules/components/ModuleItem.js
Labels: bug, [Status] Ready to Merge

#1462 Fix - Field options expand collapse icon
  assets/js/admin/form-builder.js
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  readme.txt
Labels: [Status] Ready to Merge

#1467 Fix - Disable date not working when date format is changed
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Ready to Merge

#1470 Fix - Customize approval and denial email with extra info
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/class-evf-form-task.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1461 Fix - Skip validation for hidden fields.
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Ready to Merge

#1464 Fix - Date time issue while changing date timezone.
  changelog.txt
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1469 Tweak - Change upgrade url
  addons/StyleCustomizer/includes/class-evf-style-customizer-api.php
  assets/js/admin/upgrade.js
  changelog.txt
  dist/blocks.min.js
  dist/dashboard.min.js
  dist/templates.min.js
  includes/admin/class-evf-admin-addons.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-dashboard.php
  includes/admin/class-evf-admin-menus.php
  includes/admin/views/html-admin-page-addons.php
  includes/admin/views/html-admin-settings.php
  includes/class-evf-template-loader.php
  readme.txt
  src/blocks/blocks/form-selector/Edit.js
  src/dashboard/components/Header/Header.js
  src/dashboard/screens/FreeVsPro/FreeVsPro.js
  src/dashboard/screens/Modules/components/ModuleBody.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  src/templates/components/TemplateList.tsx
Labels: Enhancement, [Status] Ready to Merge
