Repository wpeverest/everest-forms, pull requests merged in 2025-01, with the labels that each got.

#1384 Fix - Minimize the license hit when server is unavailable .
  .github/workflows/build-action-test.yaml
  .github/workflows/push-deploy.yml
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  includes/evf-core-functions.php
  readme.txt
Labels: bug

#1375 Enhancement - Captcha design Revamp.
  assets/css/admin.scss
  assets/images/captcha/cloudflare-logo.png
  assets/images/captcha/hCAPTCHA-logo.png
  assets/images/captcha/reCAPTCHA-v2-v3.png
  assets/js/admin/settings.js
  changelog.txt
  includes/admin/class-evf-admin-settings.php
  includes/admin/settings/class-evf-settings-recaptcha.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1380 Tweak - Meta key field readonly
  changelog.txt
  includes/abstracts/class-evf-form-fields.php
  readme.txt
Labels: Enhancement, Merged

#1385 Feature - User Roles and Permission
  assets/css/admin.scss
  assets/images/tools-icons/api_logs.svg
  assets/images/tools-icons/collapse-line.svg
  assets/images/tools-icons/export.svg
  assets/images/tools-icons/form_migrator.svg
  assets/images/tools-icons/import.svg
  assets/images/tools-icons/logs.svg
  assets/images/tools-icons/open.svg
  assets/images/tools-icons/payment_log.svg
  assets/images/tools-icons/roles_and_permission.svg
  assets/images/tools-icons/system_info.svg
  assets/js/admin/tools.js
  dist/rolesandpermission.min.js
  dist/rolesandpermission.min.js.LICENSE.txt
  includes/RestApi/class-evf-rest-api.php
  includes/RestApi/controllers/version1/class-evf-role-and-permission.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-settings.php
  includes/admin/class-evf-admin-tools.php
  includes/admin/views/html-admin-page-export.php
  includes/admin/views/html-admin-page-import.php
  includes/admin/views/html-admin-page-tools-logs.php
  includes/admin/views/html-admin-page-tools.php
  package.json
  src/rolesandpermission/App.jsx
  src/rolesandpermission/components/RoleAndPermissionAPI.jsx
  src/rolesandpermission/components/TrashUserRoleModel.jsx
  src/rolesandpermission/components/UserDisplayModal.jsx
  src/rolesandpermission/components/UserRoleTable.jsx
  src/rolesandpermission/index.js
  webpack.config.js
Labels: [Status] Ready to Merge, Feature Branch 🚀

#1383 Feature - SMTP settings in Everest Forms
  assets/images/evf-checked.png
  assets/images/smart-smtp-logo.png
  assets/js/admin/admin.js
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-role-and-permission.php
  includes/RestApi/controllers/version1/class-evf-templates.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-menus.php
  includes/admin/class-evf-admin-tools.php
  includes/admin/evf-admin-functions.php
  includes/admin/views/html-admin-page-smart-smtp-setup.php
  includes/class-evf-ajax.php
  readme.txt
Labels: [Status] Ready to Merge, Feature Branch 🚀

#1370 Tweak - Add mark as spam option in entries list.
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/class-everest-forms.php
  includes/class-evf-form-task.php
  includes/evf-entry-functions.php
Labels: Enhancement, [Status] Ready to Merge

#1376 Fix - Datepicker and File upload field not working in elementor popup.
  assets/js/frontend/everest-forms-file-upload.js
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Ready to Merge

#1347 Dev - Subscription plan field with trail period
  assets/css/admin.scss
  assets/css/everest-forms.scss
  assets/js/admin/form-builder.js
  changelog.txt
  everest-forms.php
  includes/abstracts/class-evf-form-fields.php
  includes/class-everest-forms.php
  includes/class-evf-forms-features.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-payment-subscription-plan.php
  readme.txt
Labels: [Status] Ready to Merge, [Status] Needs Docs, Feature Branch 🚀

#1374 Enhancement - Forms table design
  assets/css/admin.scss
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/class-evf-admin-forms.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1371 Enhancement - Approve deny entry mail
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/class-evf-admin-entries.php
  includes/class-evf-form-task.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge
