Repository wpeverest/everest-forms, pull requests merged in 2025-03, with the labels that each got.

#1419 Fix - Double rendering issue on smart phone field
  assets/js/frontend/everest-forms.js
  changelog.txt
  readme.txt
Labels: bug, [Status] Ready to Merge

#1420 Dev - Hook to add custom date format options.
  changelog.txt
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Review, [Status] Needs Test

#1397 Fix - Overall feedback issue on ajax submission
  changelog.txt
  includes/class-evf-form-task.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1387 Dev - Conditional logic based on date range
  assets/js/admin/form-builder.js
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1400 Enhance - Form preview desing revamp
  assets/css/everest-forms-default-frontend.scss
  assets/css/evf-form-preview.scss
  assets/css/variables/_colors.scss
  assets/images/save-frame.svg
  assets/images/upgrade-boost-icon.svg
  assets/js/frontend/evf-form-preview.js
  changelog.txt
  includes/class-evf-ajax.php
  includes/class-evf-shortcodes.php
  includes/class-evf-template-loader.php
  readme.txt
  templates/form-preview/evf-form-preview-template.php
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Changelog

#1422 Tweak - Display entry id in the entries list view
  changelog.txt
  includes/admin/class-evf-admin-entries-table-list.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge
