Repository wpeverest/everest-forms, pull requests merged in 2025-02, with the labels that each got.

#1401 Fix - Date field is not working properly when Disable past date is enabled.
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  includes/fields/class-evf-field-date-time.php
  readme.txt
Labels: bug, [Status] Needs Changelog, [Status] Needs Test

#1406 Fix - Arbitrary file upload issue when form submit.
  changelog.txt
  includes/abstracts/class-evf-form-fields-upload.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1392 Fix - File upload limit message not showing in the frontend.
  changelog.txt
  everest-forms.php
  includes/abstracts/class-evf-form-fields-upload.php
  includes/class-everest-forms.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1402 Tweak - Open upgrade to pro to new tab from submenu
  assets/js/admin/admin.js
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  languages/everest-forms.pot
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1411 Fix - Slot booking while the custom format is set in the WordPress timezone.
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  includes/evf-core-functions.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1408 Enhance - Activation in module flow
  assets/images/icons/alert-icon.png
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/admin/class-evf-admin-dashboard.php
  includes/evf-core-functions.php
  src/dashboard/screens/Modules/components/ModuleItem.js
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1407 Added - New settings id on header for each options
  changelog.txt
  everest-forms.php
  includes/admin/class-evf-admin-settings.php
  includes/class-everest-forms.php
  readme.txt
Labels: Enhancement, [Status] Needs Review, [Status] Needs Changelog, [Status] Needs Test

#1413 Enhance - Filter to show allowed country only on Smart Phone
  assets/js/frontend/everest-forms.js
  changelog.txt
  includes/class-evf-frontend-scripts.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1415 Enhance - New docs in dashboard
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: Enhancement
