Repository wpeverest/everest-forms, pull requests merged in 2025-05, with the labels that each got.

#1431 Feature - Clean talk anti spam integration
  addons/Addons.php
  addons/CleanTalk/Builder/Builder.php
  addons/CleanTalk/CleanTalk.php
  addons/CleanTalk/Settings/Settings.php
  addons/CleanTalk/assets/css/admin/admin.css
  addons/CleanTalk/assets/css/admin/admin.scss
  addons/CleanTalk/assets/css/admin/backward.css
  addons/CleanTalk/assets/css/admin/backward.scss
  addons/CleanTalk/assets/images/CleanTalk.png
  addons/CleanTalk/assets/js/admin/admin.js
  addons/CleanTalk/assets/js/admin/admin.min.js
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/clean-talk.webp
  assets/js/admin/settings.js
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/class-evf-ajax.php
  includes/class-evf-form-task.php
  includes/class-evf-integrations.php
  includes/shortcodes/class-evf-shortcode-form.php
  src/dashboard/Constants/Products.js
Labels: [Status] Ready to Merge, [Status] Needs Docs, Feature Branch 🚀, Tested

#1435 Tweak -User Registration & Membership logo on other products
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  readme.txt
  src/dashboard/Constants/Products.js
  src/dashboard/images/UR-logo.webp
Labels: [Status] Ready to Merge, [Status] Needs Changelog, Approved

#1425 Fix - Preserve filename in file upload
  changelog.txt
  includes/abstracts/class-evf-form-fields-upload.php
  readme.txt
Labels: bug, [Status] Ready to Merge, [Status] Needs Changelog, Approved

#1432 Feature - Private Note field on Form Builder
  addons/Addons.php
  addons/CleanTalk/Builder/Builder.php
  addons/CleanTalk/CleanTalk.php
  addons/CleanTalk/Settings/Settings.php
  assets/js/admin/form-builder.js
  assets/js/frontend/evf-form-preview.js
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-entries-table-list.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/class-evf-fields.php
  includes/class-evf-form-task.php
  includes/class-evf-template-loader.php
  includes/evf-core-functions.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-private-note.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: [Status] Ready to Merge, [Status] Needs Docs, Feature Branch 🚀

#1427 Enhance - Option to edit meta key
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  changelog.txt
  includes/class-evf-ajax.php
  includes/fields/class-evf-field-address.php
  includes/fields/class-evf-field-ai.php
  includes/fields/class-evf-field-checkbox.php
  includes/fields/class-evf-field-country.php
  includes/fields/class-evf-field-date-time.php
  includes/fields/class-evf-field-email.php
  includes/fields/class-evf-field-file-upload.php
  includes/fields/class-evf-field-first-name.php
  includes/fields/class-evf-field-hcaptcha.php
  includes/fields/class-evf-field-hidden.php
  includes/fields/class-evf-field-image-upload.php
  includes/fields/class-evf-field-last-name.php
  includes/fields/class-evf-field-likert.php
  includes/fields/class-evf-field-number.php
  includes/fields/class-evf-field-phone.php
  includes/fields/class-evf-field-privacy-policy.php
  includes/fields/class-evf-field-radio.php
  includes/fields/class-evf-field-rating.php
  includes/fields/class-evf-field-recaptcha.php
  includes/fields/class-evf-field-scale-rating.php
  includes/fields/class-evf-field-select.php
  includes/fields/class-evf-field-text.php
  includes/fields/class-evf-field-textarea.php
  includes/fields/class-evf-field-turnstile.php
  includes/fields/class-evf-field-url.php
  includes/fields/class-evf-field-wysiwyg.php
  includes/fields/class-evf-field-yes-no.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Docs

#1428 Enhance - Popup form option and customization
  changelog.txt
  dist/form-selector/block.json
  includes/blocks/block-types/class-evf-blocks-form-selector.php
  includes/shortcodes/class-evf-shortcode-form.php
  package-lock.json
  package.json
  readme.txt
  src/blocks/blocks/form-selector/Edit.js
  src/blocks/blocks/form-selector/block.json
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Docs

#1434 Feature - Tags on from
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  composer.json
  includes/Helpers/FormHelper.php
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/class-evf-admin-assets.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/class-evf-ajax.php
  includes/class-evf-post-types.php
Labels: [Status] Needs Review, [Status] Needs Docs, Feature Branch 🚀, [Status] Needs Test

#1437 Fix - Show premium sidebar enable disable issue
  assets/js/admin/admin.js
  changelog.txt
  includes/admin/views/html-admin-settings.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1438 Fix - Form creation button generating multiple form
  changelog.txt
  readme.txt
  src/templates/components/PluginStatus.tsx
Labels: bug, [Status] Ready to Merge

#1429 Fix - Text message for no forms in analytics.
  templates/emails/summary-email-body-default.php
Labels: bug, [Status] Needs Review, [Status] Needs Test

#1436 Enhance - Active and inactive post type in all forms
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  includes/admin/class-evf-admin-forms-table-list.php
  includes/class-everest-forms.php
  includes/class-evf-ajax.php
Labels: Enhancement, [Status] Needs Review, [Status] Needs Docs, [Status] Needs Changelog, [Status] Needs Test

#1433 Dev - Hook to add custom smart tag.
  changelog.txt
  includes/class-evf-smart-tags.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1430 Fix - Entry id smart tag not working in email subject.
  changelog.txt
  includes/class-evf-smart-tags.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1440 Tweak - Added settings option on form table
  changelog.txt
  everest-forms.php
  includes/admin/class-evf-admin-forms-table-list.php
  includes/class-everest-forms.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge

#1453 Enhance - Active module workflow
  changelog.txt
  includes/RestApi/controllers/version1/class-evf-modules.php
  includes/evf-core-functions.php
  readme.txt
  src/dashboard/screens/Modules/components/ModuleItem.js
Labels: Enhancement, [Status] Ready to Merge

#1447 Tweak - Edit meta key design
  assets/js/admin/form-builder.js
  changelog.txt
  readme.txt
Labels: Enhancement, [Status] Ready to Merge
