Repository wpeverest/everest-forms, pull requests merged in 2025-07, with the labels that each got.

#1468 Dev - Global setting for paypal in settings payment
  assets/css/admin.scss
  assets/extensions-json/sections/all_extensions.json
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge, [Status] Needs Docs, Feature Branch 🚀

#1466 Fix - Delete file on form entry deletion on free
  changelog.txt
  includes/class-evf-form-task.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1465 Enhance - Edit field file upload, image upload and signature from both frontend listing and admin
  assets/css/admin.scss
  assets/images/filetypes/doc.png
  assets/images/filetypes/pdf.png
  assets/images/filetypes/ppt.png
  assets/images/filetypes/xls.png
  assets/js/frontend/everest-forms-file-upload.js
  changelog.txt
  includes/Helpers/FormHelper.php
  includes/abstracts/class-evf-form-fields-upload.php
  includes/abstracts/class-evf-form-fields.php
  includes/class-evf-form-task.php
  includes/shortcodes/class-evf-shortcode-form.php
  readme.txt
Labels: Enhancement, [Status] Ready to Merge, [Status] Needs Docs

#1475 Fix - Limitation in file upload capacity in free version.
  assets/js/admin/upgrade.js
  changelog.txt
  everest-forms.php
  includes/abstracts/class-evf-form-fields-upload.php
  includes/abstracts/class-evf-form-fields.php
  includes/admin/class-evf-admin-assets.php
  includes/class-everest-forms.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1474 Fix - Style customizer template not applied to duplicate forms.
  changelog.txt
  everest-forms.php
  includes/class-everest-forms.php
  includes/class-evf-form-handler.php
  package.json
  readme.txt
Labels: bug, [Status] Ready to Merge

#1476 Fix - Avoid the API request to stats for development mode
  includes/admin/class-evf-admin-deactivation-feedback.php
  includes/class-everest-forms.php
Labels: [Status] Ready to Merge

#1478 Fix - Issue while exporting repeater field value.
  changelog.txt
  includes/abstracts/class-evf-form-fields-upload.php
  includes/export/class-evf-entry-csv-exporter.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1480 Fix - Dropdown value showing empty on entry table
  changelog.txt
  includes/admin/builder/class-evf-builder-settings.php
  includes/admin/evf-admin-functions.php
  includes/admin/views/html-admin-page-entries-view.php
  includes/evf-core-functions.php
  readme.txt
Labels: bug, [Status] Ready to Merge

#1482 Fix - Form entries table customization lost after updating the form.
  changelog.txt
  includes/class-evf-form-handler.php
  readme.txt
Labels: bug, [Status] Ready to Merge
